Climbing stairs
Lakhankumawat/LearnCPP pull request #1010
Opened 2022-03-30 06:57 UTC by Shweta2024

## Related Issue
#### Climbing Stairs:-
You are climbing a staircase. It takes n steps to reach the top.

Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?

## Proposed Changes
I have added the following things: -
-  Problem Statement
-  Examples
-  Explanation
-  Code
-  Time Complexity & Space Complexity

## Additional Info
- [Link of the problem](https://leetcode.com/problems/climbing-stairs/)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

#### Climbing Stairs

You are climbing a staircase. It takes n steps to reach the top.

Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?

We were supposed to find the total number of ways in which we can reach the n-th step, provided we can either make one jump or 2 jumps at a time.

I have added the Problem Statement and Examples along with the Explanation on how to approach this problem, a commented Code, and also written the Time Complexity and Space Complexity. And finally updated the README.md.

This change helps to solve a very famous problem of Dynamic Programming i.e. Climbing Stairs and this problem helps in understanding the concept of Dynamic Programming.

I coded this problem in VS Code and tested the given problem on the test cases in the range of 1 to 44. And it is working fine for them.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Screenshot of Output when the given input is 4|  Screenshot of Output when the given input is 44  |
| ![op1](https://user-images.githubusercontent.com/75883328/160769207-5f112722-6318-47b8-978b-b71791e0577e.png) | ![op2](https://user-images.githubusercontent.com/75883328/160769947-5e497ed9-338c-4829-a716-c97753d665c0.png)
 |

2022-03-30 11:52 UTC, Lakhankumawat requested changes

2022-03-30 11:52 UTC, Lakhankumawat commented on D-DynamicProgramming/README.md
> +
Add a working image for your problem just like others see README for more .


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-30 11:53 UTC, Lakhankumawat commented
Where is your issue number ?

2022-03-30 11:55 UTC, Lakhankumawat commented
Every PR is linked with an issue

2022-03-30 14:28 UTC, Shweta2024 commented
> Where is your issue number?

Sir, I have added the issue number please check.
Thank you

2022-04-01 05:46 UTC, Lakhankumawat approved these changes
LGTM ✨🎉

Good work @Shweta2024  , keep contributing keep shining

2022-04-01 05:46 UTC, merged

2022-04-01 05:47 UTC, Lakhankumawat commented
@all-contributors please add @Shweta2024  code ,

2022-04-01 05:53 UTC, Shweta2024 commented
> 

Thank you sir