Clone a list and random pointers
Lakhankumawat/LearnCPP pull request #1049
Opened 2022-04-02 20:34 UTC by arzitmahajan

## Related Issue
#1042 

## Proposed Changes
1.Code of clone a list with comments added 
2.Separate readme with explaination

## Additional Info
     Code is checked before submitting it is a hard level question and is asked frequently in many in interview rounds
## Checklist

- [x ] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Input 1 (Output is displayed with debugger)|
| 
![image](https://user-images.githubusercontent.com/73886210/161400173-8bcafca8-d0d3-4dc4-84af-534364334567.png)
 | Input 2|
 | 
![image](https://user-images.githubusercontent.com/73886210/161400298-c97e1d77-6693-4663-b43f-aa5588c7bdeb.png)
 |

2022-04-09 14:55 UTC, Lakhankumawat reviewed
Your code looks a bit hardcoded in main

2022-04-09 14:57 UTC, Lakhankumawat approved these changes
README looks good ✨

2022-05-07 06:52 UTC, arzitmahajan commented
@Lakhankumawat is this PR good if not give me some suggestion how to improve it?

2022-05-09 15:43 UTC, arzitmahajan commented on L-LinkedList/Clone a List with Random pointers/linked list clone.cpp
> +	second->next = third;
Okay will change this

2022-05-15 02:56 UTC, siddhi-244 commented
> @siddhi-244 Please review now the function is added

No you haven't taken the input!

2022-05-15 18:08 UTC, siddhi-244 commented on L-LinkedList/Clone a List with Random pointers/linked list clone.cpp
> +
Where Iis the closing bracket ?

2022-05-15 18:09 UTC, arzitmahajan commented
Sorry I thought separate function is needed, I have made the changes please review now

2022-05-15 18:59 UTC, arzitmahajan commented on L-LinkedList/Clone a List with Random pointers/linked list clone.cpp
> +
Sorry my mistake

2022-05-15 19:00 UTC, siddhi-244 requested changes
Can you give a more detailed approach or algorithm?

2022-05-15 20:14 UTC, arzitmahajan commented
> Can you give a more detailed approach or algorithm?

I have Attached debugged pics and Approach in read-me and I think that's all I can do to explain the code .I know it's a bit confusing as this is a hard level question.

2022-05-16 04:14 UTC, siddhi-244 approved these changes
LGTM

2022-05-16 16:05 UTC, Lakhankumawat commented
Follow the announcements in discord , why did you modified A-Array's README

2022-05-16 16:40 UTC, arzitmahajan commented
> Follow the announcements in discord , why did you modified A-Array's README

Actually I  had contributed an array based question and  while I was updating the readme for Clone a list. I thought it would be better that whenever user goes through the readme and see the heading he can simply click on the heading to go to the code page , so I updated it by adding the link.

2022-05-17 10:14 UTC, Lakhankumawat commented
![image](https://user-images.githubusercontent.com/55774240/168788488-2955f613-01dc-438a-aa34-f7caa421f6c8.png)

2022-05-18 13:52 UTC, arzitmahajan commented
done

2022-05-24 16:32 UTC, Lakhankumawat approved these changes
## LGTM 🎉✨

2022-05-24 16:32 UTC, merged