convert Decimal Number to its Binary equivalent
Lakhankumawat/LearnCPP pull request #1056
Opened 2022-04-03 21:03 UTC by aditim26

## Related Issue
-  Program for decimal to binary conversion using stack(#1055)

## Proposed Changes
- Add the program for issue #1055 
- Changes in the Readme file

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

In this PR I have added a program for converting any decimal number to its binary equivalent 

This PR is solving issue #1055 which was created by me.

Examples of the test cases are given below 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1   | Screenshot #2  |
| ----------- | ----------- |
| Code                 | Title goes here     |
|![image](https://user-images.githubusercontent.com/91279248/161448381-416a4525-9d22-48b6-aabc-f2da989e5f6b.png)  | Image goes here     |

2022-04-08 07:06 UTC, aditim26 commented
@siddhi-244 Ma'am please review my PR

2022-04-09 12:57 UTC, Mrjoy832 commented
> @siddhi-244 Ma'am please review my PR

rather than taking a,b,c,x taking some proper variable name

2022-04-09 15:08 UTC, aditim26 commented
@Mrjoy832 I have made the required changes please check

2022-04-09 15:14 UTC, Mrjoy832 commented
Your readme is not following any guidelines ...image is also not viewable

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-04-09 16:08 UTC, aditim26 commented
But sir the image is visible from my side 
![image](https://user-images.githubusercontent.com/91279248/162582026-ee82623a-63a2-49f4-8efa-d0a1cccccd4e.png)

2022-04-09 17:01 UTC, aditim26 commented
sir I have added the Image but I dont know why its not visible 
![image](https://user-images.githubusercontent.com/91279248/162583953-2bf107f7-0d2e-483c-aafe-3b839f55c8d2.png)

2022-04-09 17:11 UTC, Mrjoy832 commented
> sir I have added the Image but I dont know why its not visible 
> ![image](https://user-images.githubusercontent.com/91279248/162583953-2bf107f7-0d2e-483c-aafe-3b839f55c8d2.png)
> 

While taking the screnshot copy the image and just paste in here without any code syntax

2022-04-09 17:59 UTC, aditim26 commented
![image](https://user-images.githubusercontent.com/91279248/162582678-e84410dd-d018-4bca-8b52-630411a8cde5.png)

2022-04-09 18:01 UTC, Mrjoy832 commented
not here paste into just readme in same way

2022-04-09 18:16 UTC, aditim26 commented
Sir Please check if now its visible

2022-04-09 18:24 UTC, Mrjoy832 commented
> Sir Please check if now its visible

![image](https://user-images.githubusercontent.com/77873383/162586927-7e52a6d3-43d1-4ddc-956e-c86324b62b19.png)
Not visible

2022-04-09 18:40 UTC, aditim26 commented
Sir please review the changes now

2022-04-10 02:29 UTC, Mrjoy832 commented
> Sir please review the changes now

Nice.

2022-04-10 02:31 UTC, Mrjoy832 commented
> > Sir please review the changes now
> 
> Nice...referred to admin to merge ...work on another issue.

2022-04-10 04:27 UTC, Lakhankumawat requested changes

2022-04-10 04:27 UTC, Lakhankumawat commented on S-Stack/Decimal_to_Binary.cpp
> +#include <iostream>
Rename file to `DecimalToBinary.cpp`

2022-04-10 04:27 UTC, Lakhankumawat commented on S-Stack/README.md
> +**Time Complexity** is O(n)
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-04-10 05:14 UTC, Mrjoy832 commented
You have too many commits....I am Closing this PR, create new fresh PR on same issue with less commits.

2022-04-10 05:14 UTC, closed without merging