Added the Code for Array Operations Problem. Performed various operations such as Traversal ,Insertion, Deletion & Searching in the Array
Lakhankumawat/LearnCPP pull request #1079
Opened 2022-04-07 17:59 UTC by Shatakshi-Choudhary

## Related Issue
Array Operations #1063 

Hey @Lakhankumawat , Please Check this PR . This will introduce a new concept i.e array operations.

## Proposed Changes
- Added the code for various operations in an Array along with time complexity
- Traversal, Insertion, Deletion & Searching(Linear & Binary Search)
 

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [ ] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

Performed Operations in an Array

Inserted code for Traversal in an Array  
Inserted code for Insertion of new element in an Array
Inserted code for Deletion of any element in the Array
Inserted code for Searching elements in the Array 

arr[10]={1,2,3,4,5};
traversal(arr,size);
Output= 1 2 3 4 5 
insert(arr, 10, index, size, capacity); 
(Let index be 2)
Output= 1 2 10 3 4 5 
deletion(arr, size, index);
(Let index=4)
Output=1 2 10 3 5
linearSearch(arr, key, size);
(Let key = 10)
Output= 2
binarySearch(arr, key, size);
(Let key = 3)
Output=Not Found as binary search works only for Sorted array

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-04-08 12:23 UTC, siddhi-244 requested changes
You have committed a exe file too. Remove that ! Add a readme and follow readme guidelines

2022-04-08 13:35 UTC, Shatakshi-Choudhary commented
@siddhi-244 Sure! I will remove the exe file & add a readme.

2022-04-08 17:44 UTC, Shatakshi-Choudhary commented
@siddhi-244 , Should I edit the existing readme or create a new one? As I am very new to open source, so I don't know much more about these things.

2022-04-09 08:28 UTC, siddhi-244 commented
> @siddhi-244 , Should I edit the existing readme or create a new one? As I am very new to open source, so I don't know much more about these things.

Edit the existing one!

2022-04-09 10:33 UTC, Shatakshi-Choudhary commented
@siddhi-244 Okay! I  will edit it.

2022-04-09 13:43 UTC, Shatakshi-Choudhary commented
@siddhi-244 I have edited the README.md file. Can you please check whether it's updated or not ?

2022-04-10 07:50 UTC, siddhi-244 requested changes
Link array operations properly in table of contents

2022-04-10 08:26 UTC, Shatakshi-Choudhary commented
@siddhi-244, Is it Fine now?

2022-04-12 06:05 UTC, Shatakshi-Choudhary commented
@siddhi-244, I have made the required changes. Please Check them.

2022-04-16 05:49 UTC, siddhi-244 approved these changes
LGTM

2022-04-16 13:01 UTC, Lakhankumawat requested changes

2022-04-16 13:01 UTC, Lakhankumawat commented on A-Array/README.md
> +![Output 2](https://user-images.githubusercontent.com/87706725/162575080-7853a59b-78a6-4159-90a9-2eade886e6b8.png)
Instead of output screenshot you need to paste working screenshots of the the program 


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-04-16 14:12 UTC, Shatakshi-Choudhary commented on A-Array/README.md
> +![Output 2](https://user-images.githubusercontent.com/87706725/162575080-7853a59b-78a6-4159-90a9-2eade886e6b8.png)
Working Screenshot means? Like I have to paste the screenshot of the whole code or the output which I will get after running the program?

2022-04-16 15:46 UTC, Lakhankumawat commented on A-Array/README.md
> +![Output 2](https://user-images.githubusercontent.com/87706725/162575080-7853a59b-78a6-4159-90a9-2eade886e6b8.png)
Great Did you went through the comment i just made above , without going through it throughly you just came and post your doubt not a good thing .

2022-04-16 16:16 UTC, Shatakshi-Choudhary commented on A-Array/README.md
> +![Output 2](https://user-images.githubusercontent.com/87706725/162575080-7853a59b-78a6-4159-90a9-2eade886e6b8.png)
I am really sorry! I have read all the guidelines & also watched the videos. But I actually didn't understand this. I am very new to open source & this is my first PR as well as contribution, that's why I am not getting all these things. I will surely try to improve & understand all the things in every possible way. Sorry for the trouble from my side.

2022-04-17 09:13 UTC, Lakhankumawat approved these changes
Looks Good To Me 🎉✨

Your Code looks excellent and your readme is also good , keep learning keep contributing 

> Mention your previously merged pr numbers in your next prs and if they are also as good as this or more then i will look forward to increase the level of your next PR , which can help you get on the top on leaderboard .

And no issues you didn't knew about screenshot as i was also frustrated by contributors repeating same mistake again and again ,also everyone is beginner once so no issues in making mistakes , instead learning from them is thing to be focused upon.

2022-04-17 09:14 UTC, merged

2022-04-17 09:15 UTC, Lakhankumawat commented
@all-contributors please add @Shatakshi-Choudhary code ,

2022-04-17 09:42 UTC, Shatakshi-Choudhary commented
Thank you for merging my PR. It was really amazing experience contributing to open source. I will surely contribute more & more with the hope of learning new things.