Implementation of Shell Sort
Lakhankumawat/LearnCPP pull request #1129
Opened 2022-04-12 17:54 UTC by YasmeenKararty

## Related Issue
- Implementation of Shell Sort #231 
- I created a new pull request after resolving the merge conflicts as I was asked in my previous pull request #329 

## Proposed Changes
- Added the implementation of the Shell Sort Algorithm used for sorting arrays.

## Additional Info
- This algorithm allows sorting an array in average complexity O(N Log N)
- Sorting array by breaking it down into a number of smaller subarrays. Not necessary lists of contiguous elements. Instead, the shell sort algorithm uses an increment gap, to create the array of elements that are “gap” elements apart.
- I used the visual studio as my environment and tested it on multiple arrays as an input including this array = { 13, 20, 5, 27, 67, 72, 20, 89, 12, 18, 100} and the output is provided below.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      
| ----------- 
| Output 
|![output](https://user-images.githubusercontent.com/66736704/156751037-6cd915b9-5ea7-407e-b191-2d181735aab5.JPG)

2022-04-12 17:55 UTC, YasmeenKararty commented
@Lakhankumawat I created a new pull request as you asked me in my previous pull request #329 
Hope you can review it and merge it.

2022-05-09 15:47 UTC, YasmeenKararty commented
@Mrjoy832 I added the feature of taking the input array from the user upon your request on discord

2022-05-09 17:15 UTC, Mrjoy832 requested changes

2022-05-09 17:15 UTC, Mrjoy832 commented on S-SortingAlgorithms/README.md
> +```
remove pseudo code...add a algo point wise(Step Wise)

2022-05-09 17:39 UTC, YasmeenKararty commented on S-SortingAlgorithms/README.md
> +```
I applied the change requested, please check.
Thank you for your tolerance.

2022-05-18 11:11 UTC, YasmeenKararty commented
@Mrjoy832 Can you please review ?

2022-05-18 17:25 UTC, Mrjoy832 commented
![image](https://user-images.githubusercontent.com/77873383/169104479-115b61c5-6a48-4cce-9920-40553cd76ab6.png)
cycle sort not present as main repo..update readme

2022-05-19 11:24 UTC, YasmeenKararty commented
@Mrjoy832 Done, is there any other thing I should do?

2022-05-20 02:28 UTC, Mrjoy832 approved these changes

2022-05-20 03:35 UTC, YasmeenKararty commented
@Lakhankumawat Can you give me the next review needed ?

2022-05-20 14:11 UTC, Lakhankumawat approved these changes
## LGTM 🎉✨

Your contribution is awesome @YasmeenKararty 
Welcome to the team 🤝 , congo on first contribution being merged 💎

2022-05-20 14:11 UTC, merged

2022-05-20 14:11 UTC, Lakhankumawat commented
@all-contributors please add @YasmeenKararty code ,

2022-05-20 14:12 UTC, Lakhankumawat commented
Checkout your name in contributors list 👀