Minimum Falling Path Sum
Lakhankumawat/LearnCPP pull request #1139
Opened 2022-04-13 18:47 UTC by Shweta2024

## Related Issue
- Minimum Falling Path Sum #1118

## Proposed Changes
I have added the following things: -

- Problem Statement
- Examples
- Explanation
- Pseudo Code
- Code
- Time Complexity & Space Complexity
- Screenshot of Output

## Additional Info
- [Link of the Problem](https://leetcode.com/problems/minimum-falling-path-sum/)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

We were supposed to find the minimum sum of any falling path through the matrix provided that we can start at any element in the first row and chooses the element in the next row that is either directly below or diagonally left/right. 

I have added the Problem Statement, Examples, Explanation on how to approach this problem, a commented Code, Pseudo Code , Screenshot of the output, and written the Time Complexity and Space Complexity. And finally updated the README.md.

This change helps to solve a very famous problem of Dynamic Programming i.e. Minimum Falling Path Sum and this problem helps in understanding the concept of Dynamic Programming.

I coded this problem in VS Code and tested the given problem on the test cases in the range of 1 <= n <= 100. And it is working fine for them.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Output for matrix = [[2,1,3],[6,5,4],[7,8,9]] | Output for matrix = [[-19,57],[-40,-5]]    |
| ![image](https://user-images.githubusercontent.com/75883328/163248586-0c822b45-c3ad-4396-9d8a-9d56faeda48e.png)| ![image](https://user-images.githubusercontent.com/75883328/163248657-b7ec6bb1-0077-4646-bfd8-a613f2503976.png) |

2022-04-21 04:20 UTC, Mrjoy832 commented
LGTM🌟

2022-04-21 10:58 UTC, Lakhankumawat requested changes

2022-04-21 10:58 UTC, Lakhankumawat commented on D-DynamicProgramming/README.md
> +- [Output](#output)
Correct these links for now they are pointing somethings else if you see i've made changes in first one just for example so you can get idea .

2022-04-21 10:58 UTC, Lakhankumawat commented on D-DynamicProgramming/README.md
> +![image](https://user-images.githubusercontent.com/75883328/163241760-ba04bc09-8e7b-40a6-b974-e0031f64cf79.png)
Remove Outputs .

2022-04-21 13:25 UTC, Shweta2024 commented on D-DynamicProgramming/README.md
> +- [Output](#output)
Ok, sir got it!
Now I understood how to do it 
Thank you sir for helping

2022-04-21 13:39 UTC, Shweta2024 commented on D-DynamicProgramming/README.md
> +![image](https://user-images.githubusercontent.com/75883328/163241760-ba04bc09-8e7b-40a6-b974-e0031f64cf79.png)
The requested changes have been made, please review my PR.
Thank you sir

2022-04-22 04:07 UTC, Lakhankumawat approved these changes
LGTM ✨🎉

2022-04-22 04:08 UTC, merged

2022-04-22 04:08 UTC, Lakhankumawat commented
@all-contributors please add @Shweta2024 code ,