Calculating GCD and LCM by Recursion
Lakhankumawat/LearnCPP pull request #1152
Opened 2022-04-14 15:20 UTC by Arun9739

## Related Issue
- #1114 

## Proposed Changes
- I have added the code for finding the GCD and LCM by using recursion
- I have also updated the README.md

## Additional Info
- The answer given by the program was verified to be correct

## About the program 
- I have basically created two functions namely calculateGCD() and calculateLCM()
- calculateGCD() takes two integer inputs and returns their GCD
- It calculates the GCD recursively.
- Another function calculateLCM() calcultes the LCM by taking two inputs.
- The calculateLCM() function calls calculateGCD() so that it can directly calculate the LCM without any further iteration..
- I have updated the README.md file where I have explained in detail what is necessity of the recursion, how recusion works, what is the difference between the recursive approach and iterative approach. I have also mentioned the time complexity, space complexity, advantages and disadvantages.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/84305637/163421130-1e61a9ed-494f-4805-90f0-c25b716e1532.png)  | ![image](https://user-images.githubusercontent.com/84305637/163421286-a35b1075-f14a-4717-9558-a9182f68e280.png)  |

2022-04-14 15:23 UTC, Arun9739 commented
@Mrjoy832 please review my pr. 
This is my **second** pr.
My first sucessfully merged pr is #1045

2022-04-14 16:00 UTC, Lakhankumawat requested changes

2022-04-14 16:00 UTC, Lakhankumawat commented on R-Recursion/README.md
> +![](https://files.realpython.com/media/Thinking-Recursively-in-Python_Watermarked.1825397c00ea.jpg)
![rer](https://user-images.githubusercontent.com/55774240/163428237-caf022e8-a3a5-47ad-bba2-568b4cb8e5b9.png)

remove this image it is plagiarised from realpython

Rectify all the typos like shown in image from README , if exits .

2022-04-14 16:09 UTC, Arun9739 commented
@Lakhankumawat done the changes sir. Please review.

2022-04-15 03:55 UTC, Lakhankumawat approved these changes
LGTM ✨🎉

2022-04-15 03:56 UTC, merged

2022-04-15 03:56 UTC, Lakhankumawat commented
I think you can earn Level-2 in your next PR show more efforts and keep contributing 🤞