DNF Sort Explanation added
Lakhankumawat/LearnCPP pull request #1175
Opened 2022-04-15 16:02 UTC by Pranshu321

## Related Issue
- #1173 

## Proposed Changes
- Detail Explanation of DNF sort in readme added and code for DNF sort is already added by someone but the explanation is missing so I added that to enhance the experience.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

In this I have added a detailed explanation of DNF sort starting from what it is and ending with the disadvantages, all document was written in a simple language to be understandable easily.

DNF Sort is the sorting method that is used to sort the array only having `0's` `1's` and `2's`.

Change is required to enhance the understanding of the DNF sort.

#1173 

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-04-28 10:34 UTC, Mrjoy832 commented
LGTM🌟

2022-04-30 05:08 UTC, Lakhankumawat requested changes

2022-04-30 05:08 UTC, Lakhankumawat commented on S-SortingAlgorithms/README.md
> +
Add a working image of sorting algorithm small gif or any image which shows the process . Follow guidelines for README .

2022-04-30 07:42 UTC, Pranshu321 commented on S-SortingAlgorithms/README.md
> +
@Lakhankumawat  Working Image added.

2022-05-01 04:15 UTC, Lakhankumawat approved these changes
LGTM ✨🎉

2022-05-01 04:18 UTC, merged