Intro to inheritance
Lakhankumawat/LearnCPP pull request #1182
Opened 2022-04-16 11:40 UTC by SanyaGera

## Related Issue
-issue number #378 

## Proposed Changes
- I-Inheritance folder has been created inside the OOPs folder.
- README file has been added which consists of an overview and explanation about the concept of inheritance.
- A CPP file for Single Inheritance has been created which explains the concept of single inheritance, working of derived and base class along with its code.

## Additional Info
- No additional info

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

I have added the Inheritance concept in OOPs. So, far I have added the description about Inheritance and explanation about Single Inheritance in this Branch. The detailed files will be added after.

Inheritance is an important aspect in understanding Object Oriented Programming. This was missing from this project. Understanding inheritance, helps solve many issues for a coder.

 What types of changes does your code introduce? 
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

 Screenshots:
Code:
![image](https://user-images.githubusercontent.com/75986201/163673497-613203b6-f953-40a8-ab78-1c2f40c1f44b.png)

Output:
![image](https://user-images.githubusercontent.com/75986201/163673520-6cc20e86-a049-4498-a928-59eb2d9df49e.png)

2022-04-19 04:00 UTC, Lakhankumawat requested changes

2022-04-19 04:00 UTC, Lakhankumawat commented on O-OOPS/I-Inheritance/README.md
> +In C++, inheritance is a process in which one object acquires all the properties and behaviors of its parent object automatically. In such way, you can reuse, extend or modify the attributes and beha
I think you can still improve your README
 
1. Adding Headline navigation Links at the top
2. Adding some visual images of inheritance
3. Using ### instead of ## in naming sub headlines ( ## looks unusually long )
4.  Follow READMEi guidelines


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-04-21 03:21 UTC, Lakhankumawat commented
Any Updates ?

2022-04-21 18:07 UTC, SanyaGera commented
> Any Updates ?

I am working on it

2022-04-23 12:50 UTC, Lakhankumawat approved these changes
LGTM 🎉✨

2022-04-23 12:51 UTC, merged

2022-04-23 12:53 UTC, Lakhankumawat commented
@all-contributor please add @SanyaGera code ,

2022-04-23 12:54 UTC, Lakhankumawat commented
@all-contributors please add @SanyaGera code ,