Update README.md
Lakhankumawat/LearnCPP pull request #1196
Opened 2022-04-17 13:57 UTC by vinaya563

## Related Issue
- Issue Number (#1195 )

## Proposed Changes
-Added Readme  and description about  Circular Linked List and its applications in various domains .

## Checklist

- [ ] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [ ] 🎀 I have updated the README accordingly.
- [ ] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-04-17 14:46 UTC, Lakhankumawat commented
Make Changes inside `[L-LinkedList/C-CircularLinkedList/README.md]` and add code for it too ...

You need to modify your readme further 
1. Make sure headlines are short and follow camel casing
2. Add a working image of program ( not code or ouput screenshot)
3. Restructure README navigation links and organise it 
4. Follow the guidelines given below

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-04-17 15:30 UTC, vinaya563 commented
I have made the changes as said !

2022-04-17 17:13 UTC, Lakhankumawat commented
> I have made the changes as said !

Nope Not made all the changes yet

2022-04-17 17:55 UTC, vinaya563 commented
Now is it okay ?
If not can you please say what exactly should I change ?

2022-04-18 06:02 UTC, Lakhankumawat requested changes

2022-04-18 06:02 UTC, Lakhankumawat commented on L-LinkedList/C-CircularLinkedListkedList/README.md
> +
make the link to headlines you covered in README over here

See here
(https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md)

2022-04-19 16:31 UTC, Lakhankumawat commented
No Updates ?

2022-04-20 01:54 UTC, vinaya563 commented
Now is it fine ?
or any other changes are required ?

2022-04-20 03:16 UTC, Lakhankumawat approved these changes
LGTM 🎉✨🐱‍👤

2022-04-20 03:16 UTC, Lakhankumawat reviewed
Since there were many minor changes required .

2022-04-20 03:17 UTC, merged

2022-04-20 03:18 UTC, Lakhankumawat commented
@all-contributors please add @vinaya563 code ,