Added a program to find Union of two sorted arrays
Lakhankumawat/LearnCPP pull request #1228
Opened 2022-04-22 18:49 UTC by shivanithorve01

## Related Issue
-This issue is associated with issue #1162 

## Proposed Changes
- Added a program to find Union of two sorted arrays 
- Updated readme 

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      |
| ----------- | 
| Output  | 
| 
![image](https://user-images.githubusercontent.com/81226536/163536470-3971f593-6a1a-4be1-9461-b7e4c3981457.png) |

2022-04-22 18:59 UTC, shivanithorve01 commented
My PRs https://github.com/Lakhankumawat/LearnCPP/pull/81 and https://github.com/Lakhankumawat/LearnCPP/pull/496 is already merged into main. Please consider my PR as a higher levels.

2022-04-22 19:00 UTC, shivanithorve01 commented
If there is need of any change please let me know. I will do it ASAP.

2022-04-23 13:04 UTC, Mrjoy832 commented
Resolve conflicts

2022-04-23 16:30 UTC, shivanithorve01 commented
@Mrjoy832  Please check

2022-04-23 18:37 UTC, Mrjoy832 commented
![image](https://user-images.githubusercontent.com/77873383/164937203-29ab19fc-0323-40ac-8593-a1f6950aca2f.png)
put ticks on correct boxes

2022-04-23 18:39 UTC, Mrjoy832 commented
> ![image](https://user-images.githubusercontent.com/77873383/164937203-29ab19fc-0323-40ac-8593-a1f6950aca2f.png) put ticks on correct boxes

I have edited...from next time you will do by yourself

2022-04-23 18:40 UTC, Mrjoy832 commented
LGTM🌟

2022-04-24 04:05 UTC, Lakhankumawat requested changes

2022-04-24 04:05 UTC, Lakhankumawat commented on A-Array/README.md
> -5.Further, we can iterate through the new array from the beginning and print the elements of the array.
Great Job , You erased all this section while resolving merge conflicts .
Also there are spacing in your file name , Your file name should be CamelCased with no spacing on `-` in between .

2022-04-24 04:05 UTC, Lakhankumawat commented on A-Array/README.md
We don't need outputs .

2022-04-24 04:05 UTC, Lakhankumawat commented on A-Array/README.md
> +**Algorithm :**
Working image of approach is missing .

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-04-24 04:07 UTC, Lakhankumawat commented
Due to too many issues and erased existing README data i am closing this PR , please create a new pr with all the changes requested follow README guidelines  and mention this pr in your new pr

2022-04-24 04:07 UTC, closed without merging