KMP Algorithm
Lakhankumawat/LearnCPP pull request #1257
Opened 2022-04-25 13:52 UTC by vinaya563

## Related Issue
- Issue number (#1238 )

## Proposed Changes
- Added the implementation and required readme for the KMP Algorithm which is one of the most important string algorithms used for pattern searching.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
![image](https://user-images.githubusercontent.com/91210199/165172436-c9c43157-4196-49fa-8027-915a9c1354fb.png)

2022-04-25 18:19 UTC, Mrjoy832 commented
Use ### for Sub-headings of readme

2022-04-25 18:20 UTC, Mrjoy832 commented
Take String and key as input from user

2022-04-25 20:50 UTC, vinaya563 commented
@Mrjoy832  I have done the necessary changes ..Can you please review it now

2022-04-25 23:43 UTC, Mrjoy832 commented
LGTM🌟

2022-04-26 03:25 UTC, Lakhankumawat requested changes

2022-04-26 03:25 UTC, Lakhankumawat commented on S-StringAlgorithms/KMP/README.md
> +
Correct Links 
1. Some of them are not pointing the right thing
2. They are not line by line unlike others 
![image](https://user-images.githubusercontent.com/55774240/165213657-6dfccfc0-f864-4111-a043-3c68350a1ed0.png)


## Tip :
do this `- []` space between `-` and `[brackets]`

2022-04-26 03:25 UTC, Lakhankumawat commented on S-StringAlgorithms/KMP/README.md
> +We know that characters pat[0..j-1] match with txt[i-j…i-1] (Note that j starts with 0 and increment it only when there is a match).
If this is pseudocode then add in it ` "```" ` section
```
Like this is a pseudo code
```

2022-04-26 03:25 UTC, Lakhankumawat commented on S-StringAlgorithms/KMP/README.md
> +Space Complexity: O(m) where m is the size of the pattern.
Advantages and Disadv. are missing

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

For god sake please follow guidelines i've told you same earlier in your PR's as well.

2022-04-26 12:46 UTC, vinaya563 commented
@Lakhankumawat
 sorry for inconvenience sir...I assure you that I will not repeat the same mistakes again.
Now is it okay ??

2022-04-26 13:45 UTC, Lakhankumawat approved these changes
### LGTM ✨🎉

2022-04-26 13:46 UTC, merged

2022-04-26 13:46 UTC, Lakhankumawat commented
Good Contribution .