Removing duplicates from sorted singly linked list
Lakhankumawat/LearnCPP pull request #1264
Opened 2022-04-26 05:41 UTC by i-am-aisha

## Related Issue
#1242 

## Proposed Changes
- Create RemovingDuplicates.cpp
- Update Readme.md

## Additional Info
-Add an algorithm for removing all duplicates elements from a sorted singly linked list.
firstly I take inputs from the user in form of vector elements and then make them nodes of a linked list and then call a function which I made for remove all duplicate elements from that singly linked list.
-Add comments wherever needed
-update README.md accordingly

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Code image 1  | Code image 2    | Code image 3 |
| 
![Screenshot (344)](https://user-images.githubusercontent.com/100334178/165228827-ff5b7203-ad30-402a-bebd-39bba658e678.png)
| 
![Screenshot (345)](https://user-images.githubusercontent.com/100334178/165228948-c28a7439-6635-427e-a36b-7099642a1971.png)
|
![Screenshot (346)](https://user-images.githubusercontent.com/100334178/165229051-f3ef1610-0701-463c-8b39-f2ba4cf313b4.png)
|

Input image
![Screenshot (347)](https://user-images.githubusercontent.com/100334178/165229609-e068df2c-6810-4901-825e-150292a04a60.png)

Output image
![Screenshot (348)](https://user-images.githubusercontent.com/100334178/165229639-0a73b1c9-8ed6-4029-b7bf-3c1a3221af0f.png)

2022-04-28 09:39 UTC, Lakhankumawat requested changes

2022-04-28 09:39 UTC, Lakhankumawat commented on L-LinkedList/S-SinglyLinkedList/README.md
>  # Singly Linked List
Links to other properties like `Algorithms` or `Advantages` , `DisAdv` , `Time Complexity` is missing .

2022-04-28 17:14 UTC, i-am-aisha commented on L-LinkedList/S-SinglyLinkedList/README.md
>  # Singly Linked List
Changes updated 👍

2022-04-30 05:02 UTC, Lakhankumawat commented
Links on the top , go through this README
https://github.com/Lakhankumawat/LearnCPP/tree/main/S-SortingAlgorithms
![image](https://user-images.githubusercontent.com/55774240/166091894-76f5b0d0-569d-484b-82d8-5db5875deb9a.png)

2022-04-30 05:54 UTC, i-am-aisha commented
Changes done 👍

2022-05-01 04:10 UTC, Lakhankumawat approved these changes
LGTM ✨🎉

2022-05-01 04:10 UTC, merged