Issue #1247 resoled: Minimum number of deletions and insertions required to transform one string into another
Lakhankumawat/LearnCPP pull request #1275
Opened 2022-04-28 13:40 UTC by AastikSharma05

## Related Issue
- The problem is to tell the minimum number of insertion and deletion that need to be done in order to convert string 'a' into another string 'b'. ( #1247  )
- Added the code implementation of Minimum insertion and deletion to convert one string into another string using dp.
- Added the explanation of Minimum insertion and deletion to convert one string into another string Problem in the README.md file.

## Proposed Changes
- Added the code of Minimum insertion and deletion to convert one string into another string Problem using dp.
- Added README.md file of Minimum insertion and deletion to convert one string into another string Problem with time complexity.

## Additional Info
- This code uses dynamic programming.
- This problem is a variation of LCS problem.
- This is one of the commonly asked interview questions and the concept of this question helps us to solve many more problems.'
- This code solves an open issue #1247 
- I have tested these changes on VS code using multiple inputs and matched the output with the expected output.
- This change will not affect or create conflict with any other code.
- Time complexity: O(M*N)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Code Snippet  | Readme Snippet    |
| ![code](https://user-images.githubusercontent.com/84850243/165157332-dcfb5742-cda1-4664-9351-24c2eebf365d.png) | ![readme](https://user-images.githubusercontent.com/84850243/165157436-013be789-3427-4ae9-bc03-68e68a5bef3d.png)   |

2022-04-28 13:42 UTC, AastikSharma05 commented
@Mrjoy832  I am really sorry. Somehow the previous PR got closed if you don't mind can you please review this pr again .

2022-04-28 13:44 UTC, Mrjoy832 commented
![image](https://user-images.githubusercontent.com/77873383/165766286-2479dae3-c824-46cd-9a4c-b4d78fc9e38d.png)
do it

2022-04-28 13:44 UTC, AastikSharma05 commented
Done

2022-04-28 13:46 UTC, Mrjoy832 commented
LGTM🌟

2022-04-29 03:20 UTC, Lakhankumawat requested changes

2022-04-29 03:20 UTC, Lakhankumawat commented on D-DynamicProgramming/MinimumInsertionDeletion.cpp
> +int lcs(string str1, string str2, int m, int n)
Add Comments to your code

2022-04-29 03:48 UTC, AastikSharma05 commented
Added the comments in the CPP file @Lakhankumawat.

2022-04-29 12:53 UTC, Lakhankumawat approved these changes
🎉✨

2022-04-29 12:54 UTC, merged

2022-04-29 12:54 UTC, Lakhankumawat commented
@all-contributors please add @AastikSharma05 code ,