Diagonal traversal
Lakhankumawat/LearnCPP pull request #1300
Opened 2022-05-01 18:05 UTC by utkarsh006

## Related Issue
- Title Diagonal Traversal #1296

## Proposed Changes
- I have added the following things: -
- Problem Statement
- Examples
- Algorithm
- Code
- Time Complexity & Space Complexity

## Additional Info
[LINK OF THE PROBLEM STATEMENT](https://practice.geeksforgeeks.org/problems/diagonal-traversal-of-binary-tree/1)
## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

We were supposed to display the diagonal traversal of the binary tree.

I have added the Problem Statement, Examples, an Algorithm on how to approach this problem, a commented Code, and written the Time Complexity and Space Complexity. And finally updated the README.md.

This change helps to solve a very famous problem of Binary Trees i.e. Diagonal Traversal of Binary Tree and this problem helps in understanding the concept of Trees in depth.

I coded this problem in VS Code and tested the given problem on the test cases in the range: 1 <= Number of nodes<= 105,
1 <= Data of a node<= 105. And it is working fine for them.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Input : [1,2,3,4,null,5,6,null,null,7,8,9]  | Input : [1,2,3,null,null,4,5]    |
| ![image](https://user-images.githubusercontent.com/94545831/166158390-b3499180-0489-4db5-9ceb-839e6d3866e6.png) | ![image](https://user-images.githubusercontent.com/94545831/166158576-c839336a-407a-47a0-98a8-1b6b0c148ace.png)  |

2022-05-02 07:15 UTC, Mrjoy832 commented
Can You add an index at top of the readme please?? only taking name of all existing traversal

2022-05-02 07:35 UTC, utkarsh006 commented
Yes surely I will do this ASAP :)

2022-05-02 16:05 UTC, utkarsh006 commented
> Can You add an index at top of the readme please?? only taking name of all existing traversal

@Mrjoy832 I have made the requested changes :) Please review it .

2022-05-02 18:00 UTC, Mrjoy832 approved these changes

2022-05-02 18:00 UTC, Mrjoy832 commented
LGTM🌟

2022-05-02 18:17 UTC, Lakhankumawat requested changes

2022-05-02 18:17 UTC, Lakhankumawat commented on T-Tree/T-TreeTraversals/README.md
> +# CONTENTS
`Contents` Follow Camelcasing

2022-05-02 18:17 UTC, Lakhankumawat commented on T-Tree/T-TreeTraversals/README.md
> +# DIAGONAL TRAVERSAL
Came Casing ` Diagonal Traversal`

2022-05-02 18:17 UTC, Lakhankumawat commented on T-Tree/T-TreeTraversals/README.md
> +## PROBLEM STATEMENT
Camel

2022-05-02 18:17 UTC, Lakhankumawat commented on T-Tree/T-TreeTraversals/README.md
> +- SPACE COMPLEXITY : O(N)
Camel Casing

2022-05-02 18:20 UTC, Lakhankumawat commented
I have an offer for you @utkarsh006  do me a favour and i will increase level of your pr 
Visit this https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md and improve the README like this , Like 
1. table of contents at the top 
2. remove output screenshots from morris sort and modify it too a little bit .
3. Add a working image of morris sort above just like you did for your sort .

2022-05-02 18:32 UTC, utkarsh006 commented
> I have an offer for you @utkarsh006 do me a favour and i will increase level of your pr Visit this https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md and improve the README like this , Like
> 
> 1. table of contents at the top
> 2. remove output screenshots from morris sort and modify it too a little bit .
> 3. Add a working image of morris sort above just like you did for your sort .
I am so sorry I cant perform the above given tasks as I dont know about Morris Traversal of Binary Tree and secondly my college exams are going on. I hope you understand :) Hoping for a positive response.

2022-05-03 16:55 UTC, Lakhankumawat commented
Do the reqired changes other than the changes which i offered ( optional ones )

2022-05-04 05:40 UTC, utkarsh006 commented
> Do the reqired changes other than the changes which i offered ( optional ones )
@Lakhankumawat 
I have done the required camel casing changes !

2022-05-04 08:29 UTC, Lakhankumawat approved these changes
## LGTM 🎉✨

2022-05-04 08:30 UTC, merged

2022-05-04 08:31 UTC, Lakhankumawat commented
@all-contributors please add @utkarsh006 code ,