Zig Zag level Order Traversal in Tree
Lakhankumawat/LearnCPP pull request #1315
Opened 2022-05-02 18:28 UTC by Pranshu321

## Related Issue
- #1314 

## Proposed Changes
-  Cpp file added
- Readme Updated

## Additional Info
In this, I have explained in a very simple how a zig-zag traversal is performed and how it should be approached.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

#1314 

In any GCC compiler.

- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots
| Screenshot #1      |
| ----------- | 
| Output Screenshot| 
![image](https://user-images.githubusercontent.com/86917304/166304059-dd248d91-2ca2-4913-bcda-93634396c457.png)

2022-05-04 08:38 UTC, Mrjoy832 commented
Resolve conflict

2022-05-04 11:53 UTC, Pranshu321 commented
> Resolve conflict

Resolved Sir @Mrjoy832

2022-05-05 13:45 UTC, Mrjoy832 commented
Resolve Branch Conflict

2022-05-05 14:38 UTC, Pranshu321 commented
> Resolve Branch Conflict

Now check sir , @Mrjoy832

2022-05-06 07:25 UTC, Mrjoy832 requested changes

2022-05-06 07:25 UTC, Mrjoy832 commented on T-Tree/T-TreeTraversals/Zig_Zag_level_Order_Traversal.cpp
> +}
Add some comments

2022-05-11 12:31 UTC, Pranshu321 commented on T-Tree/T-TreeTraversals/Zig_Zag_level_Order_Traversal.cpp
> +}
> Add some comments

Sir added , Sorry for delay @Mrjoy832

2022-05-11 16:02 UTC, Mrjoy832 commented
https://github.com/Lakhankumawat/LearnCPP/blob/main/T-Tree/T-TreeTraversals/zigzag_levelorderTraversal.cpp
It's already merged ..Sorry but I am closing Yours

2022-05-11 16:03 UTC, closed without merging