Queue using stacks
Lakhankumawat/LearnCPP pull request #1321
Opened 2022-05-03 07:15 UTC by AyuBisht

## Related Issue
- We are given a stack data structure with push and pop operations, the task is to implement a queue using instances of stack data structure and operations on them. (#1317 )

## Proposed Changes
Implemented queue using stacks data structure. Performs three operations:
-enqueue: pushes an element to the queue
-dequeue: pops an element from the queue
-empty: tells whether the queue is empty or not

## Additional Info
Queue is a data structure that uses FIFO (first in first out) principle. Stack on the i

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots

![image](https://user-images.githubusercontent.com/94152085/166416168-58f09112-1eba-43bc-ba10-da323c450649.png)
![image](https://user-images.githubusercontent.com/94152085/166416264-06a56e20-8964-4a3b-9f54-6f793c4920e3.png)
![image](https://user-images.githubusercontent.com/94152085/166416292-bb8af952-5ca8-4575-bd3c-d37f330bab9c.png)

OUTPUT
| ![image](https://user-images.githubusercontent.com/94152085/166416407-9f1858c5-7b72-4dbf-af62-c786325fd21d.png)  |

2022-05-03 07:17 UTC, AyuBisht commented
@Mrjoy832 @miraj0507 please review this pr.

2022-05-03 09:30 UTC, Mrjoy832 requested changes

2022-05-03 09:30 UTC, Mrjoy832 commented on Q-Queue/README.md
> +![queue using stacks](https://www.interviewbit.com/blog/wp-content/uploads/2021/11/Stack-Example-1024x640.png)
Remove the image insert another one as it has logo of another website it will be considered as plagarised

2022-05-03 09:30 UTC, Mrjoy832 commented on Q-Queue/README.md
> +1. Time Complexity :
Add Space Complexity

2022-05-03 09:31 UTC, Mrjoy832 commented
![image](https://user-images.githubusercontent.com/77873383/166431766-a4fdc8a3-de62-44cc-8505-dd6f14c64e86.png)
do it

2022-05-03 15:29 UTC, AyuBisht commented
@Mrjoy832 is it alright now?

2022-05-03 18:24 UTC, Mrjoy832 requested changes

2022-05-03 18:24 UTC, Mrjoy832 commented on Q-Queue/README.md
> +
Attach algorithm

2022-05-04 12:45 UTC, AyuBisht commented on Q-Queue/README.md
> +
@Mrjoy832  I have already added the pseudo code, for all the three operations further down in the README

2022-05-04 15:38 UTC, Mrjoy832 approved these changes

2022-05-04 15:38 UTC, Mrjoy832 approved these changes

2022-05-05 04:52 UTC, Lakhankumawat approved these changes
## LGTM 🎉✨

2022-05-05 04:52 UTC, merged

2022-05-05 04:52 UTC, Lakhankumawat commented
@all-contributors please add @AyuBisht code ,