Introduction to recursion
Lakhankumawat/LearnCPP pull request #1325
Opened 2022-05-03 13:41 UTC by SanyaGera

## Related Issue
-# issue number #1320 

## Proposed Changes
- Made changes in the README file. I added the following topics:
   -Addition of table of contents and navigation links
   -Addition of definition and syntax of recursion
   -Addition of advantages of recursion
   -Addition of disadvantages of recursion
-Added an Introduction to Recursion CPP file containing a basic program on recursion for its explanation.
   

## Additional Info
- No additional Info

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Code:
![image](https://user-images.githubusercontent.com/75986201/166463646-f0b0ddb5-ebfa-475e-85ec-c47e43a77a0a.png)
Output:
![image](https://user-images.githubusercontent.com/75986201/166463839-cfd88ea3-d73f-43c6-b57d-589ccf8144e6.png)

2022-05-04 08:47 UTC, Mrjoy832 requested changes

2022-05-04 08:47 UTC, Mrjoy832 commented on R-Recursion/README.md
> +    -
remove

2022-05-04 08:47 UTC, Mrjoy832 commented on R-Recursion/README.md
> +  - [Recursion](#recursion)
![image](https://user-images.githubusercontent.com/77873383/166649448-8ad173a7-0d35-4663-9194-f88feedb51da.png)
- spelling error
- Add a state Space tree diagram explaining Tracing of Recusrion

2022-05-06 07:19 UTC, Mrjoy832 requested changes

2022-05-06 07:19 UTC, Mrjoy832 commented on R-Recursion/Introduction-to-Recursion.cpp
> +using namespace std;
remove this only keep factorial and show tracing of factorial in readme ......change the PR title accordingly

2022-05-06 07:21 UTC, Mrjoy832 requested changes

2022-05-06 07:21 UTC, Mrjoy832 commented on R-Recursion/README.md
> +    - [Tracing of a recursive function](#tracing-of-a-recursive-function)
on this point add tracing of factorial with state space tree

2022-05-07 13:53 UTC, Mrjoy832 approved these changes

2022-05-07 13:54 UTC, Mrjoy832 commented
@Lakhankumawat , Kindly review this one

2022-05-08 06:48 UTC, Lakhankumawat commented
Recursion folder is changing too much these days , i've told a contributor to organise it , i'll see this pr after it is done .
Also remove the underscore in file name 
File name must be camel cased without any space

There are too many issues in this Pr 
Links in README are not working
there are two code files and the contribution is too basic i.e. factorial using recursion .

2022-05-08 07:28 UTC, Mrjoy832 commented
@SanyaGera resolve conflicts

2022-05-08 07:37 UTC, SanyaGera commented
Hello @Lakhankumawat @Mrjoy832 , I understand that there are several issues and pull requests being made on recursion everyday. That is why, I created this PR which organizes the README file into topics and subtopics. 
Also, I checked it again and all the links in README are working on my end, if there is some error please let me know.
And the purpose for including a basic file factorial-using-recursion is that I wanted to show tracing of recursion using a basic code and this advise was given to me by @Mrjoy832 sir. 
I hope you will take my PR under consideration.
Thank you

2022-05-10 08:49 UTC, Lakhankumawat commented
I would recommend you to create a new add the required changes and **do not add unnecessary files or lines in README , one c++ file with README only** ,  pr dm me pr number on discord and close this one as there are a lot of changes 

File name must be camel cased with no spacing or underscore in between , just add `FactorialUsingRecursion` and no introduction add necessary changes regarding in README.

2022-05-10 08:49 UTC, closed without merging