Count Prefix Using Trie
Lakhankumawat/LearnCPP pull request #1327
Opened 2022-05-03 18:35 UTC by Pranshu321

## Related Issue
- #1316 

## Proposed Changes
- Cpp file added
- Readme File Added

## Additional Info
- In, This I have explained how we can count the prefix of word or we say the words that start with that prefix and return the count of that.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

In this, I have deeply explained how we approach the question of what should be the node structure and also written well commented code which make more understanding of topic.

Prefix count using trie

#1316 

Any GCC Compiler

- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots
| Screenshot #1      |
| ----------- | 
| Code Output | 
![image](https://user-images.githubusercontent.com/86917304/166519935-b8b9eb52-43e4-4829-a3ce-e65f7b59cf17.png)

2022-05-04 16:07 UTC, siddhi-244 commented on T-Trie/Count_Prefix.cpp
> +    string check = "th"; // The prefix which we have to check.
Try to take this as input !

2022-05-07 06:33 UTC, Pranshu321 commented on T-Trie/Count_Prefix.cpp
> +    string check = "th"; // The prefix which we have to check.
Done @siddhi-244 , Please review it

2022-05-07 06:36 UTC, Pranshu321 commented
> Can you check the approach once?

And yes, I have checked the approach and don't worry mam @siddhi-244

2022-05-11 12:27 UTC, Pranshu321 commented
> > Can you check the approach once?
> 
> And yes, I have checked the approach and don't worry mam @siddhi-244

@siddhi-244 please review this

2022-05-13 17:25 UTC, Pranshu321 commented
> Add table of contents in the readme.

@siddhi-244 added

2022-05-13 17:27 UTC, siddhi-244 approved these changes
LGTM

2022-05-16 04:19 UTC, Lakhankumawat requested changes

2022-05-16 04:19 UTC, Lakhankumawat commented on T-Trie/README.md
> +
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-05-16 12:07 UTC, Pranshu321 commented on T-Trie/README.md
> +
Now check sir , the guidelines followed

2022-05-16 15:52 UTC, Lakhankumawat approved these changes
## LGTM 💎🚩

2022-05-16 15:52 UTC, merged