Head Recursion
Lakhankumawat/LearnCPP pull request #1348
Opened 2022-05-05 17:14 UTC by i-am-aisha

## Related Issue

## Proposed Changes
Create a HeadRecursion.cpp code file with mentioning proper comments and code of head recursion in super easy and understandable way.
updated readme accordingly to the change in folder types of recursion.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

## Output Screenshots
code images
![Screenshot (17)](https://user-images.githubusercontent.com/100334178/166976532-227f75a6-4a03-4a21-941e-c492f0b813e5.png)

Input image
![Screenshot (15)](https://user-images.githubusercontent.com/100334178/166976715-3030b6ad-adf1-4678-95e0-529ba887d235.png)
output image
![Screenshot (16)](https://user-images.githubusercontent.com/100334178/166976849-1f69da46-8f98-453a-b284-c4ded1539579.png)

2022-05-07 09:47 UTC, Mrjoy832 requested changes

2022-05-07 09:47 UTC, Mrjoy832 commented on R-Recursion/Types of Recursion/README.md
> +we pass n=5 in the function fun, each time call for function with value n-1 without printing it at first. As a result, fun(1) will be the first to execute completely and 1 is printed first. The funct
write algo using some points

2022-05-07 10:40 UTC, i-am-aisha commented on R-Recursion/Types of Recursion/README.md
> +we pass n=5 in the function fun, each time call for function with value n-1 without printing it at first. As a result, fun(1) will be the first to execute completely and 1 is printed first. The funct
updated 👍

2022-05-08 08:20 UTC, i-am-aisha commented
@Mrjoy832 I have updated the changes please have a look on it.

2022-05-08 16:22 UTC, Mrjoy832 requested changes

2022-05-08 16:22 UTC, Mrjoy832 commented on R-Recursion/Types of Recursion/README.md
> +  - [Algorithm](#head-recursion)
![image](https://user-images.githubusercontent.com/77873383/167305361-6d85f95c-57ac-4c5a-8278-240701173003.png)
At the top Table of Content is not properly done as there Only Tree Recursion mentioned..kindly remove and make it better

2022-05-08 16:46 UTC, i-am-aisha commented on R-Recursion/Types of Recursion/README.md
> +  - [Algorithm](#head-recursion)
![Screenshot (26)](https://user-images.githubusercontent.com/100334178/167306405-b64154d3-f708-487d-a5d2-ce5f456a2d9a.png)
 @Mrjoy832  Hope now its fine.

2022-05-12 14:27 UTC, Mrjoy832 commented
LGTM🌟

2022-05-13 14:14 UTC, Lakhankumawat approved these changes
LGTM ✨🎉

2022-05-13 14:14 UTC, merged