Power2
Lakhankumawat/LearnCPP pull request #1352
Opened 2022-05-06 12:55 UTC by utkarsh006

## Related Issue
- Power of 2 #1351

## Proposed Changes
- I have added the following things: -
- Problem Statement
- Examples
- Algorithm
- Code
- Time Complexity & Space Complexity

## Additional Info
[LINK OF THE PROBLEM STATEMENT](https://leetcode.com/problems/power-of-two/)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

We were supposed to find if a number can be represented as power of two.

I have added the Problem Statement, Examples, an Algorithm on how to approach this problem, a commented Code, and written the Time Complexity and Space Complexity. And finally updated the README.md.

This change helps to solve a very famous problem of Recursion i.e. Power of Two and this problem helps in understanding the concept of Recursion in depth.

I coded this problem in VS Code and tested the given problem on the test cases in the range: -231 <= n <= 231 - 1. And it is working fine for them.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Input : 16  | Input : 5   |
|![image](https://user-images.githubusercontent.com/94545831/167134864-ef54486a-c5c6-4866-89e9-aa83e175addd.png)|![image](https://user-images.githubusercontent.com/94545831/167134962-7acf0faa-4371-4218-91e0-9a9916452d28.png)|

2022-05-07 09:59 UTC, Mrjoy832 commented
Add one index in the readme top kindly as there are many numbers of questions

2022-05-07 12:15 UTC, utkarsh006 commented
> Add one index in the readme top kindly as there are many numbers of questions

I have done the required changes

2022-05-07 13:52 UTC, Mrjoy832 approved these changes

2022-05-07 15:00 UTC, Lakhankumawat requested changes

2022-05-07 15:00 UTC, Lakhankumawat commented on R-Recursion/Power_of_two.cpp
> +SPACE COMPLEXITY : O(N)   */
File name must be camel cased `PowerOfTwo.cpp`

2022-05-07 15:35 UTC, utkarsh006 commented on R-Recursion/Power_of_two.cpp
> +SPACE COMPLEXITY : O(N)   */
> File name must be camel cased `PowerOfTwo.cpp`

Done the changes kindly review @Lakhankumawat

2022-05-08 06:15 UTC, Lakhankumawat approved these changes
LGTM ✨🎉

2022-05-08 06:15 UTC, merged

2022-05-08 06:16 UTC, Lakhankumawat commented
Contiuous Good Contribution -1 [ CGC ]
mention this pr number in your next pr and if i found it eligible and there are some efforts in the pr i will increase the level of that pr.