Computing path matrix from powers of adjacency matrix
Lakhankumawat/LearnCPP pull request #1353
Opened 2022-05-06 17:10 UTC by VaishnaviMandloi

## Related Issue
- #1344  

## Proposed Changes
- added implementation code forPath Matrix .
- added a explanation in readme file with image.

## Additional Info
- Computing path matrix from its adjacency matrix by multiplying adjacency matrix with itself , a[i][j] represent the number of paths of path length of p (p = power of matrix) from vertex i yo j.
- changes are made in only G-Graph folder.
-1st file : PathMatrix.cpp
-2nd file: readme.md
-tested with many input , screenshot of one of those is provided below.
-time complexity O(p(n^3)) , where n is total vertex and p is the power of adjacency matrix .

## Checklist

- [ ] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [ ] 🎀 I have updated the README accordingly.
- [ ] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | 
| ----------- | 
| Output  | 
| 
![output #1344](https://user-images.githubusercontent.com/98760492/167179956-52903c14-d288-436c-b1f0-628614cf7f9b.png)
  |

2022-05-07 09:54 UTC, Mrjoy832 requested changes

2022-05-07 09:54 UTC, Mrjoy832 commented on G-Graphs/README.md
> +            for (j : 1 to n) do
- Add algorithm not pseudo Code
- Add space Complexity
- Add your PR into G-Graph/I-Implementition

2022-05-07 09:54 UTC, Mrjoy832 commented on G-Graphs/PathMatrix.cpp
> +    }
Add more comments in Code

2022-05-07 15:22 UTC, VaishnaviMandloi commented on G-Graphs/PathMatrix.cpp
> +    }
kindly review my pr now , changes are made as told 
added comment ,change file location of PathMatrix to Graph-implementation folder and  updated readme of Graph-Implementation folder

2022-05-07 18:31 UTC, Mrjoy832 commented
3 files are changed why?

2022-05-08 03:47 UTC, VaishnaviMandloi commented
> 3 files are changed why?

Readme phele graph folder ki update ki thi ...phir PathMatrix.cpp file Graph-implementation folder mai move kri to readme bhi graph-implementation wale folder ki update kri. Isliye 3 file h 
1. Readme jo graph folder mai h wo empty h
2. Readme jo graph-Implementation folder mai h wo updated h
3. PathMatrix.cpp file

2022-05-08 07:18 UTC, Mrjoy832 requested changes

2022-05-08 07:18 UTC, Mrjoy832 commented on G-Graphs/README.md
> +# Table of content
Keep it as same as master branch

2022-05-08 08:48 UTC, VaishnaviMandloi commented on G-Graphs/README.md
> +# Table of content
Made the required change , now review  it please..

2022-05-09 02:01 UTC, Mrjoy832 requested changes

2022-05-09 02:01 UTC, Mrjoy832 commented on G-Graphs/I-Implementation/Readme.md
> +- [Path Matrix](#path-matrix])
link not working

2022-05-09 05:01 UTC, VaishnaviMandloi commented on G-Graphs/I-Implementation/Readme.md
> +- [Path Matrix](#path-matrix])
Made the required changes , please check now

2022-05-09 17:19 UTC, Mrjoy832 approved these changes

2022-05-09 17:21 UTC, Mrjoy832 commented
@Lakhankumawat , as G-Graphs readme is already empty and her changes in Readme of G-Graphs will not affect,So I referred You ..
LGTM🌟

2022-05-10 09:05 UTC, Lakhankumawat approved these changes
LGTM 💻🎉✨

2022-05-10 09:05 UTC, merged

2022-05-10 09:07 UTC, Lakhankumawat commented
Mention this pr number in your next pr i will increase prs level , you have continuous good contribution , i value your efforts but i cannot yours prs to level2 continuously so we are having level1 here , hopee you understand ,

2022-05-10 09:50 UTC, VaishnaviMandloi commented
> Mention this pr number in your next pr i will increase prs level , you have continuous good contribution , i value your efforts but i cannot give yours prs to level2 continuously so we are having level1 here , hope you understand ,

 

> 

@Lakhankumawat  yea I understand 😁 , exited for more contributions..