N-Candy Problem
Lakhankumawat/LearnCPP pull request #1361
Opened 2022-05-06 19:42 UTC by RajAdwaita

## Related Issue
#1357 
## Proposed Changes
- Change 1 -> Added Code for the Problem
- Chnage 2 -> Added a detailed README file for better understanding

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

2022-05-06 19:43 UTC, RajAdwaita commented
Please do not review this PR now, I need to append some more work , which will be done soon.

2022-05-18 05:35 UTC, Mrjoy832 requested changes

2022-05-18 05:35 UTC, Mrjoy832 commented on D-DynamicProgramming/N-CandyProblem/README.md
> +
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Put your readme into D-DynamicProgramming/readme.md

2022-05-18 05:35 UTC, Mrjoy832 commented
- put  ticks on all suitable boxes

2022-06-12 11:02 UTC, closed without merging