Word Wrap Problem
Lakhankumawat/LearnCPP pull request #1389
Opened 2022-05-08 09:51 UTC by Purvak-10

## Related Issue
- Word Wrap Problem, issue no. #1387

## Proposed Changes
- Given ‘n’ words of various lengths, and a limit on the number of characters that can be put in one line. Assume each word has length less than the width of line. You have to arrange these given words in line.

## Checklist

- [ ] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [ ] 🎀 I have updated the README accordingly.
- [ ] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
- Let take an array A={aaa, bbb, cc, dddd} and length of line=6.

![wwp](https://user-images.githubusercontent.com/76229635/167290873-42f18641-cb83-40ea-8531-1770a55c3261.jpg)

2022-05-08 10:01 UTC, Purvak-10 commented
@Mrjoy832 Please check my pr for issue no. #1387.

2022-05-08 16:24 UTC, Mrjoy832 requested changes

2022-05-08 16:24 UTC, Mrjoy832 commented on P-Problem Statements & Solution/3-Level 3/Readme.md
> +
Add your content into level 2 and add index at top of readme

2022-05-08 18:29 UTC, Purvak-10 commented on P-Problem Statements & Solution/3-Level 3/Readme.md
> +
@Mrjoy832 Please review, i have done the changes.

2022-05-09 01:56 UTC, Mrjoy832 requested changes

2022-05-09 01:56 UTC, Mrjoy832 commented on P-Problem Statements & Solution/2-Level 2/WordWrapProblem.cpp
> +}
Add MORE COMMENTS

2022-05-09 01:56 UTC, Mrjoy832 commented on P-Problem Statements & Solution/2-Level 2/Readme.md
> +### Output
remove this new file add your content into the existed readme of level-2

2022-05-09 13:29 UTC, Purvak-10 commented on P-Problem Statements & Solution/2-Level 2/Readme.md
> +### Output
@Mrjoy832 please review, i have done the changes.

2022-05-09 17:23 UTC, Mrjoy832 commented
We cannnot accept this much  Commits for single PR..**I am Closing this** create fresh PR with less commits on same issue

2022-05-09 17:25 UTC, closed without merging