Hash table and Linear probe Resolution method for Customer Details
Lakhankumawat/LearnCPP pull request #1395
Opened 2022-05-08 15:55 UTC by Arun9739

## Related Issue
- #1374 

## Proposed Changes
- Added a file for Hash Table of Customer details
- Updated the Readme accordingly

## Additional Info
- The code was tested well and the results are in well manner.

To store a customer details and search them in well manner, we use a Hash Table. In Hash table we enter the data in Linear hashing method and search them based on the same method. if we encounter any collision, we resolve it by using a Linaer probe resolution method.

The customer details contain :
- Customer name
- Customer Id
- customer phone

The functions used in the program : 
- insert() : To insert a data into the HashTable
- search() : To search whether a data is present in the hash table
- display() : To dispaly the Hash Table 

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | 
| ----------- | 
| ![image](https://user-images.githubusercontent.com/84305637/167304323-6b9c690d-4948-4f3c-8af0-1f075a7ea85a.png)     |

2022-05-08 15:56 UTC, Arun9739 commented
@Mrjoy832 Please review my pr

This is my third pr. My first two successful pr's are :
- #1046 
- #1152

2022-05-08 16:16 UTC, Mrjoy832 commented
Keep a short name od CPP file

2022-05-09 08:28 UTC, Arun9739 commented
@Mrjoy832 renamed the cpp file succesfully

2022-05-10 18:28 UTC, Mrjoy832 commented
> @Mrjoy832 renamed the cpp file succesfully

check imp-announcement in LearnCPP Discord channel

2022-05-10 18:29 UTC, Mrjoy832 requested changes

2022-05-10 18:29 UTC, Mrjoy832 commented on H-HashTable/README.md
> +```
add advantages and disadvantages

2022-05-11 08:53 UTC, Arun9739 commented
@Mrjoy832 done the changes sir

2022-05-13 13:49 UTC, Lakhankumawat approved these changes
LGTM ✨🎉

2022-05-13 13:49 UTC, merged

2022-05-13 13:49 UTC, Lakhankumawat commented
Good Contribution .