Adding cpp file and readme
Lakhankumawat/LearnCPP pull request #1406
Opened 2022-05-10 11:00 UTC by miretteamin

## Related Issue
- Issue #1305 

## Proposed Changes
- I added the implementation of the algorithm.
- I updated the Readme file accordingly.

## Additional Info
- Readme has all the information and also I included comments in the code.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

I implemented subset generation algorithm using bit masking.
This algorithm prints all possible subsets from a given array with any data type.

Bit masking is faster than using ordinary operators and consumes less memory.

I included 2 examples, the first one was testing an integer array and I took this test from Subset problem on Leetcode, and the second test was testing a character array.

I ran my tests on Visual Studio Community 2019, CPP compiler.
The 2 tests are included in the screenshots.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Code Screenshot | Tests Screenshot |
| ![image](https://user-images.githubusercontent.com/29145628/166833610-e23a21a9-15d2-4a07-8b08-b0628c00bf6c.png)  | ![image](https://user-images.githubusercontent.com/29145628/166833542-3ebe2762-16ce-4442-9ab4-c03d7059354d.png)  |

2022-05-11 09:46 UTC, Mrjoy832 requested changes

2022-05-11 09:46 UTC, Mrjoy832 commented on B-BitManipulation/SubsetsGeneration.cpp
> +}
add more comments on code

2022-05-11 16:11 UTC, Mrjoy832 approved these changes

2022-05-11 16:12 UTC, Mrjoy832 commented
LGTM🌟

2022-05-13 13:40 UTC, Lakhankumawat requested changes

2022-05-13 13:40 UTC, Lakhankumawat commented on B-BitManipulation/README.md
> +![image](https://user-images.githubusercontent.com/29145628/166822363-aa8d8e4f-b358-4e35-99b3-ea5ad492597b.png)
Remove this section we don't require outputs anymore

2022-05-13 13:40 UTC, Lakhankumawat commented on B-BitManipulation/README.md
> +Algorithm that uses bit masking to generate all possible subsets from a given array with a chosen data type.<br>
Add a working image of algorithm 

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-05-14 05:10 UTC, Lakhankumawat approved these changes
## Looks Awesome ✅

2022-05-14 05:11 UTC, merged

2022-05-14 05:20 UTC, Lakhankumawat commented
Continuous Good Contribution , mention this pr number in your next pr and your next pr will have higher changes of getting higher level if found eligible .

2022-05-14 11:50 UTC, miretteamin commented
> Continuous Good Contribution , mention this pr number in your next pr and your next pr will have higher changes of getting higher level if found eligible .

Thank you!!!!