Minimum Cost Of Ropes
Lakhankumawat/LearnCPP pull request #1408
Opened 2022-05-10 13:42 UTC by utkarsh006

## Related Issue
- Minimum Cost of ropes #1407

## Proposed Changes
- I have added the following things: -
- Problem Statement
- Examples
- Algorithm
- Code
- Time Complexity & Space Complexity

## Additional Info
[LINK OF THE PROBLEM STATEMENT](https://practice.geeksforgeeks.org/problems/minimum-cost-of-ropes-1587115620/1)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

We were supposed to find the minimum cost of multiple ropes so that they can be connected with each other.

I have added the Problem Statement, Examples, an Algorithm on how to approach this problem, a commented Code, and written the Time Complexity and Space Complexity. And finally updated the README.md.

This change helps to solve a very famous problem of Heap i.e. Minimum Cost Of Ropes and this problem helps in understanding the concept of Heap.

I coded this problem in VS Code and tested the given problem on the test cases in the range: 1 ≤ N ≤ 100000 and 
1 ≤ arr[i] ≤ 106. And it is working fine for them.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
|Input : n= 4 and arr[]={4,3,2,6}| Input : n= 5 and arr[]={4,2,7,6,9}|
|![image](https://user-images.githubusercontent.com/94545831/167642304-68597b9b-b72d-47ba-a1f7-c33bcbcb061c.png)|![image](https://user-images.githubusercontent.com/94545831/167642470-6850c3f1-7949-45d4-9030-079f402e0c4e.png)|

2022-05-10 18:18 UTC, Mrjoy832 approved these changes

2022-05-10 18:19 UTC, Mrjoy832 commented
LGTM🌟

2022-05-11 08:02 UTC, utkarsh006 commented
@Lakhankumawat Review my pr and kindly upgrade the level if you find it legible. My previous pr's were 
1385
1352
1337
1300

2022-05-13 13:38 UTC, Lakhankumawat commented
Remove `Of` from file name

2022-05-15 13:19 UTC, utkarsh006 commented
@Lakhankumawat Kindly merge my Pr since I have done the requested changes. Also, upgrade the level of my Pr if you found it legible.

2022-05-16 04:18 UTC, Lakhankumawat requested changes

2022-05-16 04:18 UTC, Lakhankumawat commented on H-Heap/README.md
> +There are given N ropes of different lengths, we need to connect these ropes into one rope. The cost to connect two ropes is equal to sum of their lengths.
No Image ?

2022-05-16 17:51 UTC, utkarsh006 commented
@Lakhankumawat I have added the image

2022-05-17 05:00 UTC, Lakhankumawat approved these changes
## LGTM ✨🎉🦖

2022-05-17 05:01 UTC, merged

2022-05-17 05:02 UTC, Lakhankumawat commented
Next PR you'll get Level2 , i can't give level2 to you , although your contribution is good 

Keep Hustling 💎