Ford Fulkerson Graph Algorithm
Lakhankumawat/LearnCPP pull request #1441
Opened 2022-05-15 08:42 UTC by Pranshu321

## Related Issue
- #1429 

## Proposed Changes
- Cpp File added
- Readme Added

## Additional Info
 In this, I have explained this graph-based algorithm Ford-Fulkerson algorithm which is a greedy approach for calculating the maximum possible flow in a network or a graph.
- Well-explained code with useful comments.
- Well explained readme file.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

Enhance the understanding of the Ford-Fulkerson algorithm.

Any GCC compiler

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | 
| ----------- | 
| Code Output | 
![image](https://user-images.githubusercontent.com/86917304/168464479-8ad807c0-ebf3-43c9-a4f8-b00a266a9e60.png)

2022-05-16 11:15 UTC, Mrjoy832 approved these changes

2022-05-16 11:16 UTC, Mrjoy832 requested changes

2022-05-16 11:16 UTC, Mrjoy832 commented on G-GraphAlgorithms/README.md
Add a Demo image of it

2022-05-16 12:02 UTC, Pranshu321 commented on G-GraphAlgorithms/README.md
@Mrjoy832  Image added

2022-05-17 11:49 UTC, Mrjoy832 approved these changes

2022-05-17 11:50 UTC, Mrjoy832 commented
LGTM 🌟

2022-05-17 15:30 UTC, Lakhankumawat approved these changes
## LGTM 💎🦖

2022-05-17 15:31 UTC, merged