Issue 1459
Lakhankumawat/LearnCPP pull request #1460
Opened 2022-05-17 10:02 UTC by Shatakshi-Choudhary

## Related Issue
- Diamond Problem in Inheritance #1459 

## Proposed Changes
- Solved the Diamond Problem in Inheritance
- Added the code for the solution to the Diamond Problem

## Additional Info
- The diamond problem in Inheritance is solved by using the "virtual" keyword. We will make the two-child classes i.e B & C (who inherit from the same parent class i.e A) into virtual classes in order to avoid two copies of the parent class(class A) in the child class.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

My code consists of the solution to the problem in multiple inheritance i.e known as Diamond Problem.

The Parent class(class A) constructor is called twice: once when the B class object is created and next when the C class object is created. The properties of the A class are inherited twice, giving rise to ambiguity.

My code fixes this issue #1459 

Tested the code by creating object of the sub-child class

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
|             Screenshot #1                |                  Screenshot #2  |
| The Diamond Problem  |                  Solved Problem     |
| ![Diamond1](https://user-images.githubusercontent.com/87706725/168784856-7e84c78f-56f5-4367-8e29-860f968a5389.PNG) |    ![Diamond2](https://user-images.githubusercontent.com/87706725/168784934-76455c12-7616-43aa-8281-42dd8bdaa66f.PNG) |

2022-05-17 10:09 UTC, Lakhankumawat requested changes
You need to have only one cpp file with one README changes

2022-05-17 10:10 UTC, Lakhankumawat commented
![image](https://user-images.githubusercontent.com/55774240/168787563-3102f8a0-8e71-4cab-b2c4-dc5c4266b60c.png)


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-05-17 11:54 UTC, Mrjoy832 requested changes

2022-05-17 11:54 UTC, Mrjoy832 commented on O-OOPS/virtualFunctions.cpp
> +
Why this is changed?

2022-05-17 11:56 UTC, Mrjoy832 requested changes

2022-05-17 11:56 UTC, Mrjoy832 commented on O-OOPS/README.md
> +
Your readme is incorrect 


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-05-17 11:57 UTC, Shatakshi-Choudhary commented on O-OOPS/virtualFunctions.cpp
> +
This issue was already created by someone. That's why I deleted my issue.

2022-05-18 05:40 UTC, Mrjoy832 commented
Star the repo and put tick on **Starred repo**

2022-05-18 05:44 UTC, Mrjoy832 requested changes

2022-05-18 05:44 UTC, Mrjoy832 commented on O-OOPS/README.md
> +
- problem statement
- example
- images
- algo/approach
- time & space complexity
- advantages & disadvantages

2022-05-20 01:36 UTC, Mrjoy832 approved these changes

2022-05-20 01:37 UTC, Mrjoy832 commented
## LGTM🌟

2022-05-24 04:18 UTC, Lakhankumawat approved these changes
## LGTM ✨🎉

2022-05-24 04:19 UTC, merged

2022-05-24 04:24 UTC, Shatakshi-Choudhary commented
Thank You!!