Count no. of Set Bits
Lakhankumawat/LearnCPP pull request #1488
Opened 2022-05-18 16:47 UTC by utkarsh006

## Related Issue
- Count no. of Set Bits #1487

## Proposed Changes
- I have added the following things: -
- Problem Statement
- Examples
- Algorithm
- Code
- Time Complexity & Space Complexity

## Additional Info
[LINK OF THE PROBLEM STATEMENT](https://practice.geeksforgeeks.org/problems/set-bits0143/1)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

We were supposed to find the no. of set bits in a given number.

I have added the Problem Statement, Examples, an Algorithm on how to approach this problem, a commented Code, and written the Time Complexity and Space Complexity. And finally updated the README.md.

This change helps to solve a very famous problem of Bit Manipulation i.e. Count no. of set bits and this problem helps in understanding the concept of Bit Manipulation.

I coded this problem in VS Code and tested the given problem on the test cases in the range: 1 ≤ N ≤ 10^9. And it is working fine for them.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
|Input : N = 6|Input : N = 8|
|![image](https://user-images.githubusercontent.com/94545831/169097375-3723ad6f-cc32-4e15-b144-dd8bc99626d4.png)|![image](https://user-images.githubusercontent.com/94545831/169097528-10ed6708-8ac7-446a-b5e5-ec972b774bf9.png)|

2022-05-18 18:24 UTC, Mrjoy832 requested changes

2022-05-18 18:24 UTC, Mrjoy832 commented on B-BitManipulation/README.md
> +
explain what is set bit ..for better understanding of visitors

2022-05-18 18:24 UTC, Mrjoy832 commented on B-BitManipulation/README.md
> +- Do Bitwise AND operation of that number to its preceding number.
Which loop are you talking of?
- explain the algo properly

2022-05-18 18:33 UTC, Mrjoy832 commented
# Added Readme
## LGTM🌟

2022-05-18 18:42 UTC, utkarsh006 commented
@Lakhankumawat Kindly review this pr. My previous Pr's were : 1300,1337,1352,1385,1408

2022-05-19 03:45 UTC, Lakhankumawat approved these changes
LGTM 🚩

Minor contribution , your Pr is not eligible for Level2 for such minor contributions also your contribution has a duplication raid .

2022-05-19 03:45 UTC, merged