Adding Vertical order Traversal of binary tree
Lakhankumawat/LearnCPP pull request #270
Opened 2022-03-03 07:20 UTC by Chahat-M

## Related Issue
- #84 

## Proposed Changes
- Added vertical order traversal of a binary tree using level order traversal along with time complexity

## Additional Info
- There are various methods for the same, but here it is being implemented using level order traversal.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
![image](https://user-images.githubusercontent.com/76607503/156515418-1b53f060-f0b7-4601-b01c-56ca289b8104.png)

2022-03-03 08:01 UTC, Lakhankumawat requested changes
Your Code is unefficient and hardcoded , please improve it !!.

2022-03-12 08:56 UTC, Chahat-M commented
@Lakhankumawat Can you please clarify the above doubt, so that I can work accordingly on it again?

2022-03-13 10:37 UTC, Lakhankumawat requested changes

2022-03-13 10:37 UTC, Lakhankumawat commented on T-Tree/T-TreeTraversals/verticalTraversal.cpp
> +    root->right->right->left->right->right = new Node(12);
this you are doing here ! , is not a good appraoch

2022-03-13 10:37 UTC, Lakhankumawat commented on T-Tree/T-TreeTraversals/verticalTraversal.cpp
> +    root->right->right->left->right->right = new Node(12);
Instead you can use a for  or while loop to make it more efficient and elegant

2022-03-13 10:39 UTC, Lakhankumawat commented
1. Edit Your PR descriptive and describe your PR in a bit of details .

2022-03-13 10:40 UTC, Lakhankumawat commented
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-13 10:40 UTC, Lakhankumawat commented
once you re done these changes and one of mentors reviews your PR , your PR will be merged , thanks .

2022-03-13 11:00 UTC, Chahat-M commented on T-Tree/T-TreeTraversals/verticalTraversal.cpp
> +    root->right->right->left->right->right = new Node(12);
I was thinking of asking the user to input inorder and preorder traversal of the binary tree to create the specific tree as desired? What are your views on this?

2022-03-13 11:01 UTC, Chahat-M commented
Thanks for reviewing. I'll make the changes and update  soon.

2022-03-16 11:29 UTC, Chahat-M commented
@Lakhankumawat I have updated the code and README accordingly. Are there any more changes to be done?

2022-03-27 07:36 UTC, siddhi-244 commented on T-Tree/README.md
> +```
Add time complexity in readme

2022-03-27 08:21 UTC, Chahat-M commented on T-Tree/README.md
> +The time complexity for the same is O(n * logn), where n is the no. of total nodes.
I have already added the time complexity here.

2022-03-27 08:23 UTC, siddhi-244 commented on T-Tree/README.md
> +The time complexity for the same is O(n * logn), where n is the no. of total nodes.
Try to include it in a separate heading. You can check other prs !

2022-03-27 08:49 UTC, Chahat-M commented on T-Tree/README.md
> +The time complexity for the same is O(n * logn), where n is the no. of total nodes.
Done!!

2022-03-27 08:54 UTC, siddhi-244 commented on T-Tree/README.md
> +
Add space Complexity too

2022-03-27 17:42 UTC, Chahat-M commented on T-Tree/README.md
> +
Done!

2022-04-02 11:21 UTC, siddhi-244 requested changes
Follow the readme template.  Add table of contents

2022-05-15 03:00 UTC, siddhi-244 commented
> @siddhi-244 The table of contents should include the contents of Vertical order traversal or all the various traversals?

For the one which you have done !

2022-05-19 04:07 UTC, aditi944 commented
closed

2022-05-19 05:28 UTC, siddhi-244 approved these changes
LGTM

2022-05-20 14:15 UTC, Lakhankumawat approved these changes
## LGTM ✨💎

Your contribution is awesome @Chahat-M 🚩

Welcome to the team 🤝
Checkout your name on contributors list 🦖
Congo on your first pr being merged 🎀

2022-05-20 14:16 UTC, merged

2022-05-20 14:17 UTC, Lakhankumawat commented
@all-contributors please add @Chahat-M code ,