Add Egg Dropping Problem to Dynamic Programming folder
Lakhankumawat/LearnCPP pull request #310
Opened 2022-03-03 20:01 UTC by SidharthSarangi

## Related Issue
-  Add Egg Dropping Puzzle problem issue  #215 

## Additional Info
Link to the Problem [Link](https://www.geeksforgeeks.org/egg-dropping-puzzle-dp-11/)

## Checklist

- [`x`] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [`x`] 🎀 I have updated the documentation accordingly.
- [`x`] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

 ##### Describe your changes in detail 
 I have added the fully working code for the problem egg dropping puzzle and changed the readme file accordingly and added all required information regarding the problem and explained there the working of the code with examples and provided important links.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

2022-03-06 15:21 UTC, SidharthSarangi commented
Please review it @Lakhankumawat @iamgunjan @miraj0507 ,I have added the file and also updated the readme

2022-03-08 03:26 UTC, Lakhankumawat commented
Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. **Starr the repo if you haven't !**
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-08 06:47 UTC, SidharthSarangi commented
Added the Problem statement and uploaded the screenshots as said.

2022-03-08 06:54 UTC, SidharthSarangi commented
starred the repo and uploaded the screenshots and also added the problem
statement with link. Also I am new to open source/ Github, so I am still
learning a lot of things and unaware of all functionality of github so
please help with the rest to get it merged. Looking forward to
contribute with many more solutions/code.

On Tue, Mar 8, 2022 at 8:57 AM LakhanKumawat ᵖ⁺ ***@***.***>
wrote:

> Let me show you how to check the check list , there should be no space
> inside brackets like [x]
> [x]
>
>    - Checklist
>    - Or you can just check them from outside without doing any of these
>    - ✨ I have added tests to cover my changes.
>    - 🚩 All new and existing tests passed.
>    - 🌟 ed the repo
>
>
>    1. *Starr the repo if you haven't !*
>    2. Have you watched this video <https://youtu.be/kIFwqp9B7pQ> ?
>
> ///----------------------PR README --------------------///
>
> You need to follow particular guidelines for your README , please follow
> these guidelines click here
> <https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms>
> also you can see how your README should look like see here
> <https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md>
> for more please go through these here <https://youtu.be/7UgC3HDETRA>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Lakhankumawat/LearnCPP/pull/310#issuecomment-1061368236>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASXM2FKE4VU7SDTXWOCQ5IDU63CIVANCNFSM5P3PEGQQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-09 11:08 UTC, SidharthSarangi commented
Please check now @Lakhankumawat @iamgunjan

2022-03-13 14:55 UTC, SidharthSarangi commented
Please review it cause I want to work on other files/folder/topics and getting this merged will let me keep in mind what exactly I am supposed to do while creating a pull request. Thank You. @Lakhankumawat @iamgunjan

2022-03-16 06:34 UTC, Lakhankumawat requested changes
Modify Readme and code implementation , change function and variable names atleast instead of copy pasting everything from gfg directly

2022-03-16 06:35 UTC, Lakhankumawat requested changes
Also i don't think you followed README stylings in fact i mentioned earlier in comments 

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms)
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md)
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-16 07:59 UTC, SidharthSarangi commented
I have now updated the Readme the way you said following proper styling and the code/logic is completely mine except the driver code which is common.

2022-03-17 08:30 UTC, Lakhankumawat approved these changes
LGTM

2022-03-20 08:14 UTC, SidharthSarangi commented
Please review @iamgunjan

2022-03-23 14:40 UTC, miraj0507 commented
LGTM

2022-03-24 20:44 UTC, SidharthSarangi commented
Can someone mention why is it not getting merged? Even after I fixed everything I was required to do @Lakhankumawat @miraj0507

2022-03-25 03:13 UTC, siddhi-244 commented
> Can someone mention why is it not getting merged? Even after I fixed everything I was required to do @Lakhankumawat @miraj0507

Hey please resolve the merge conflicts!

2022-03-25 03:38 UTC, n4i9kita reviewed
LGTM.

Good job.

2022-03-25 03:38 UTC, n4i9kita commented on D-DynamicProgramming/EggDroppingPuzzle.cpp
> +class Solution
I think you should avoid making a Solution class in this problem. 
Is there any benefit here of doing so?

Also, I would recommend that you mention the header files that are being used explicitly, rather than `bits/stdc++.h`

2022-03-25 07:50 UTC, SidharthSarangi commented on D-DynamicProgramming/EggDroppingPuzzle.cpp
> +class Solution
#### Why we use class instead of function?
By using classes, you're ensuring that methods are only used on one set of data. This adds to the security of the code because you're less likely to use functions where they don't belong.

**P.S-** I get what you are trying to say but using class is a good practice when writing big programs.
             "bits/stdc++.h" I will take care of that from next time I am committing something.

2022-03-27 15:22 UTC, SidharthSarangi commented
> 



> > Can someone mention why is it not getting merged? Even after I fixed everything I was required to do @Lakhankumawat @miraj0507
> 
> Hey please resolve the merge conflicts!

I have resolved the merge conflicts please review!

2022-03-29 11:47 UTC, Lakhankumawat approved these changes
Your Contribution looks great 🌟🎉

And since it is your second PR and it is reviewed good by all mentors and you might also be frustrated by now let me increase the level of your contribution seeing your efforts 🎉

2022-03-29 11:48 UTC, merged

2022-03-29 11:48 UTC, Lakhankumawat commented
@all-contributors please add @SidharthSarangi  code ,