Manacher's Algorithm For (Longest Palindromic Substring)
Lakhankumawat/LearnCPP pull request #315
Opened 2022-03-03 22:08 UTC by singhkunal01

## Related Issue
- [ADD] Manacher's Algorithm For (Longest Palindromic Substring) #76 

## Proposed Changes
- I have added the short and crisp explanation with comments and code, You can check if something better i can do Let Me Know !!

## Additional Info
- Manacher’s Algorithm helps us find the longest palindromic substring in the given string in better complexity then the Brute Force Solution also the Dynamic Programming Solution in Linear Time and Linear Space.It will reduce the number of expands for the each index it saves the length of previously occured palindrome length.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Main Code  | Code with Solution     |
|![Manacher1](https://user-images.githubusercontent.com/76788100/156660685-3c2dca20-0f5a-45be-b3d6-57530ccabbbd.png) | ![Mancher2](https://user-images.githubusercontent.com/76788100/156660856-95cc7a54-408d-40fd-82ce-f9ec1c31121c.png)    |

2022-03-05 18:57 UTC, singhkunal01 commented
hey @miraj0507 is it everything fine ?

2022-03-13 04:36 UTC, Lakhankumawat commented
1. Delete the unncessary `png` Files 
2. Fetch Upstream And EDIT README of the folder according to your algorithm
3. Uncheck all the checks which do not apply to you

2022-03-13 04:36 UTC, Lakhankumawat commented
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-13 14:07 UTC, singhkunal01 commented
Sure i will change all the changes you want @Lakhankumawat give me some time.

2022-03-27 06:47 UTC, siddhi-244 commented on D-DynamicProgramming/ManachersAlgorithm/ManachersAlgorithm.cpp
> +
Try to add this explanation in Readme

2022-04-17 21:18 UTC, singhkunal01 commented
Hi @Lakhankumawat  can you please help me that what are you waiting for ?? Is there any problem in my solution ?

2022-04-20 15:16 UTC, siddhi-244 requested changes
can uh explain the  approach a bit more in form of steps ?

2022-05-16 04:16 UTC, siddhi-244 commented
Closing this pr!

2022-05-16 04:16 UTC, closed without merging