Rod Cutting Problem using Dynamic Programming
Lakhankumawat/LearnCPP pull request #331
Opened 2022-03-04 11:38 UTC by michaelehab

## Related Issue:
Rod Cutting Problem using Dynamic Programming #245 

## Proposed Changes
- Added the cpp solution file in /D-DynamicProgramming.
- Updated Readme.md file 

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Function Screenshot
![function_screenshot](https://user-images.githubusercontent.com/29122581/156756523-be53fad5-0021-430a-b9a7-943d0af077fe.jpg)
## Output Screenshot
![output_screenshot](https://user-images.githubusercontent.com/29122581/156756527-ff064edf-6492-4ecf-bf84-58bd9b5cd539.jpg)
## Readme Screenshot
![readme_screenshot](https://user-images.githubusercontent.com/29122581/156756529-28883f37-3b72-4032-a3ab-f57b390f123e.jpg)

2022-03-27 07:59 UTC, siddhi-244 commented
Resolve the conflicts

2022-04-12 04:48 UTC, siddhi-244 requested changes
Can uh explain the approach a bit more?

2022-04-17 19:01 UTC, michaelehab commented
This is a famous dynamic programming problem, the approach is already explained in the readme file please check it carefully.

2022-04-20 15:20 UTC, siddhi-244 commented
> This is a famous dynamic programming problem, the approach is already explained in the readme file please check it carefully.

Do the changes and solve merge conflicts too !

2022-04-20 16:57 UTC, michaelehab commented
@siddhi-244 
Excuse me, Which changes?
Alright, I'll solve the conflicts in the Readme file then you'll keep ignoring this PR for another 2 months.
I prefer that someone responsible checks this PR cause I don't think you're taking this seriously.
Thanks.
@Lakhankumawat

2022-04-21 02:57 UTC, siddhi-244 commented
> @siddhi-244 Excuse me, Which changes? Alright, I'll solve the conflicts in the Readme file then you'll keep ignoring this PR for another 2 months. I prefer that someone responsible checks this PR cause I don't think you're taking this seriously. Thanks. @Lakhankumawat

Sure !

2022-04-21 03:29 UTC, Lakhankumawat requested changes
Do the required changes , i'll resolve the merge conflicts for you and i'll merge your PR then

2022-04-21 03:29 UTC, Lakhankumawat commented on D-DynamicProgramming/README.md
> +**Space Complexity :** O(n)
1. Decrease Time Complexity font size it looks unusually big for now

2022-04-21 03:29 UTC, Lakhankumawat commented on D-DynamicProgramming/README.md
> +Given a rod of length n and a list of rod prices of length i, where 1 <= i <= n, find the optimal way to cut the rod into smaller rods to maximize profit.
2. Add some working image of rod cutting problem here like [this one](https://www.codesdope.com/staticroot/images/algorithm/rod1.png)

2022-04-21 03:29 UTC, Lakhankumawat commented on D-DynamicProgramming/README.md
> +=======
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-04-21 15:07 UTC, michaelehab commented
@Lakhankumawat Thank you for your clarification, Please check the latest commit and tell me if you need any further changes.

2022-04-22 15:57 UTC, Lakhankumawat approved these changes
LGTM ✨🎉

2022-04-22 16:00 UTC, merged

2022-04-22 16:01 UTC, Lakhankumawat commented
@all-contributors please add @michaelehab code ,