#195 (Infix to Postfix expression conversion(application of stack))
Lakhankumawat/LearnCPP pull request #366
Opened 2022-03-05 06:52 UTC by VaishnaviMandloi

## Related Issue
   Infix to Postfix expression conversion(application of stack) #195 

## Proposed Changes
- Change 1
    added implementation code for Infix to Postfix expression conversion with comments (explanation) and sample expression.
- Change 2
   added a explanation for Infix to Postfix expression conversion in README file with links and image.

## Additional Info
- It is a application of stack

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| code screenshot | output screenshot |
| ![code #195 learncpp](https://user-images.githubusercontent.com/98760492/156871428-e3cc2e23-d176-42cd-8508-821f416186aa.png)  |    ![output #195 learncpp](https://user-images.githubusercontent.com/98760492/156871605-196593de-b893-4422-8be2-81eef085a087.png) |

2022-03-05 06:59 UTC, siddhi-244 requested changes
There are a lot of blank spaces in the cpp file. Make sure you delete these spaces. Also try to follow the readme structure and explain more about the algo !

2022-03-05 14:18 UTC, siddhi-244 requested changes
Please avoid copy pasting the information from gfg. Try to write it on your own !

2022-03-05 14:21 UTC, siddhi-244 commented
///--------------------Pull Requests--------------------///

1. Short Description or CheckLists

Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.


///-----------------CheckList-------------------------///


Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.

2022-03-05 15:19 UTC, VaishnaviMandloi commented
Now I have made changes as mentioned by you please check .

2022-03-06 03:52 UTC, siddhi-244 commented on S-Stack/InfixToPostfix.cpp
> +    string expression ="a^(b*c-d/(e+f))";
Can uh take the string as input from the user here?

2022-03-06 04:57 UTC, VaishnaviMandloi commented on S-Stack/InfixToPostfix.cpp
> +    string expression ="a^(b*c-d/(e+f))";
Okay I will modify the code

2022-03-06 07:53 UTC, VaishnaviMandloi commented
@siddhi-244 Now is it better ? please check .

2022-03-06 08:24 UTC, siddhi-244 approved these changes
LGTM

2022-03-06 08:30 UTC, VaishnaviMandloi commented
thanks @siddhi-244

2022-03-08 12:54 UTC, VaishnaviMandloi commented
@siddhi-244 I updated the description if it is enough please remove the tag of short description

2022-03-10 04:46 UTC, VaishnaviMandloi commented
@iamgunjan please review it.

2022-03-10 08:06 UTC, Lakhankumawat commented
1. Star the repo 
2. Uncheck all the points in checklists which do not apply to you

2022-03-10 08:31 UTC, VaishnaviMandloi commented
@Lakhankumawat  Is it now correct?

2022-03-12 03:55 UTC, Lakhankumawat commented
LGTM 💯

2022-03-12 03:56 UTC, merged

2022-03-12 03:56 UTC, Lakhankumawat commented
@all-contributors please add @VaishnaviMandloi  code ,