Primediv
Lakhankumawat/LearnCPP pull request #402
Opened 2022-03-06 03:19 UTC by Anuragkr07

## Related Issue
- #401

## Proposed Changes
- Added a code to express a number as a sum of prime numbers if possible. Otherwise Print -1.
- updated the readme file

## Additional Info
-  This code uses the Sieve of Eratosthenes method which is a method used for finding prime numbers from 0-n.
- This is one of the commonly asked interview questions and the concept of this question helps us to solve many more problems based on prime numbers.
- This code solves an open issue #401  
- I have tested these changes on VS code and online compiler gdb using multiple inputs and matched the output with the expected output.
- This change will not affect or create conflict with any other code
- Time Complexity : O(n*log(log(n)))
- Space Complexity:  O(n)  as a vector is used for storing all the numbers.

## Checklist

- [x]  ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Code Screenshot  | Output Screenshot     |
| ![Image goes here](https://user-images.githubusercontent.com/86841935/156907725-29f06758-8ef9-4036-88b5-b930e704c5b1.JPG)  |  ![Image goes here](https://user-images.githubusercontent.com/86841935/156907729-881e6afe-f87c-41d8-b0b4-6cc576628262.JPG)  |

2022-03-06 09:29 UTC, Lakhankumawat commented
Just add all your changes first then commit at last to minimise the number of commits , more number of commits makes it difficult for mentors to review your code , but do not close this PR , will go with this but keep these things in mind for next time.

2022-03-06 09:51 UTC, Anuragkr07 commented
> Just add all your changes first then commit at last to minimise the number of commits , more number of commits makes it difficult for mentors to review your code , but do not close this PR , will go with this but keep these things in mind for next time.

okay sir..will keep this in mind from the next time

2022-03-06 14:09 UTC, siddhi-244 commented on M-MathematicalAlgorithms/README.md
> +
Please try to minimize the number of blank spaces !

2022-03-06 15:22 UTC, Anuragkr07 commented on M-MathematicalAlgorithms/README.md
> +
> Please try to minimize the number of blank spaces !

I have made the changes. Please review it

2022-03-07 05:54 UTC, Anuragkr07 commented
@siddhi-244 please check it.. I have made the changes you insisted

2022-03-07 06:50 UTC, Anuragkr07 commented
@Lakhankumawat sir please check it

2022-03-07 06:51 UTC, siddhi-244 requested changes
Add time complexity in readme

2022-03-07 08:39 UTC, siddhi-244 approved these changes
LGTM

2022-03-07 08:43 UTC, Anuragkr07 commented
> Add time complexity in readme

@siddhi-244 done.. Please check

2022-03-07 09:10 UTC, Anuragkr07 commented
@Lakhankumawat sir please check

2022-03-09 07:36 UTC, iamgunjan commented
It's good to go @Lakhankumawat

2022-03-09 07:37 UTC, iamgunjan approved these changes

2022-03-09 08:10 UTC, Lakhankumawat commented
LGTM 🦖

2022-03-09 08:10 UTC, merged

2022-03-09 08:11 UTC, Lakhankumawat commented
@all-contributors please add @Anuragkr07  code ,