#395: Created a C++ file and updated readme for Shortest Common Super-sequence
Lakhankumawat/LearnCPP pull request #465
Opened 2022-03-08 08:17 UTC by AastikSharma05

## Related Issue
- Given two strings str1 and str2, the task is to find the length of the shortest string that has both str1 and str2 as subsequences. (please mention issue number #395  )\
- Added the code implementation of Shortest Common Super-sequence Problem using dp.
- Added the explanation of Shortest Common Super-sequence Problem in the README.md file.

## Proposed Changes
- Added the code of Shortest Common Super-sequence Problem using dp.
- Added README.md file of Shortest Common Super-sequence Problem with time and space complexity.

## Additional Info
- This code uses dynamic programming.
- This problem is a variation of LCS problem.
- This is one of the commonly asked interview questions and the concept of this question helps us to solve many more problems.
- This code solves an open issue #395 
- I have tested these changes on VS code using multiple inputs and matched the output with the expected output.
- This change will not affect or create conflict with any other code
- Time Complexity : O(m*n)
- Space Complexity: O(m*n)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

Issue: #395 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Readme preview  | Code Snippet     |
| ![Screenshot 2022-03-08 134618](https://user-images.githubusercontent.com/84850243/157195191-398789cd-ec8f-4d11-b213-4b002fe107d1.png) | ![Screenshot 2022-03-06 140830](https://user-images.githubusercontent.com/84850243/156915623-9e7edce6-3bd0-4103-a76b-bd8e7390c6ef.png) |

2022-03-09 13:39 UTC, AastikSharma05 commented
please review my pr @iamgunjan @miraj0507

2022-03-17 03:51 UTC, Lakhankumawat commented
Resolve the conflicts manually

2022-03-20 04:15 UTC, AastikSharma05 commented
I have resolved the conflict so please review my pr and tell if anything needs to be done @siddhi-244 @Lakhankumawat

2022-03-23 02:10 UTC, AastikSharma05 commented
@siddhi-244 @miraj0507 @Lakhankumawat plz review it

2022-03-23 14:42 UTC, miraj0507 commented
Hey, kindly take an user input in the main function

2022-03-24 02:38 UTC, AastikSharma05 commented
@miraj0507 I have made the changes

2022-03-24 17:26 UTC, miraj0507 commented
LGTM

2022-04-02 15:05 UTC, AastikSharma05 commented
If everything is fine then please merge this pr @Lakhankumawat

2022-04-12 10:16 UTC, n4i9kita reviewed
LGTM

2022-04-16 15:50 UTC, Lakhankumawat requested changes

2022-04-16 15:50 UTC, Lakhankumawat commented on D-DynamicProgramming/README.md
> +
Add a working image 


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-04-16 15:52 UTC, Lakhankumawat requested changes

2022-04-16 15:52 UTC, Lakhankumawat commented on D-DynamicProgramming/Shortest_Common_Super-sequence.cpp
> +// C++ program to find length of the
Rename code file to `ShortestCommonSuperSequence.cpp`

2022-04-17 06:24 UTC, AastikSharma05 reviewed
I have made all the changes.

2022-04-17 06:28 UTC, AastikSharma05 commented
@Lakhankumawat Please check now.

2022-04-17 09:21 UTC, Lakhankumawat approved these changes
LGTM 🎉✨

2022-04-17 09:22 UTC, merged

2022-04-17 09:22 UTC, Lakhankumawat commented
@all-contributors please add @AastikSharma05 code

2022-04-17 09:25 UTC, Lakhankumawat commented
Looking at your contribution type , contribution  efforts and 2 merged prs  i am increasing the level of PR 

CGC= Continuous Good Contribution

2022-04-18 10:18 UTC, AastikSharma05 commented
Thanks a lot @Lakhankumawat .