Stock Buy And Sell
Lakhankumawat/LearnCPP pull request #483
Opened 2022-03-09 05:40 UTC by PrashantVIT1

Question link:
https://leetcode.com/problems/best-time-to-buy-and-sell-stock/

Added code with appropriate comments
and time & space complexity

## Related Issue
- Stock Buy And Sell (# 70)

## Proposed Changes
- added new problem statement

## Additional Info
- Any additional information or context

## Checklist

- [ ] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [ ] 🎀 I have updated the README accordingly.
- [ ] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

2022-03-09 05:42 UTC, PrashantVIT1 commented
#70 Stock Buy And Sell

2022-03-09 05:42 UTC, siddhi-244 commented
///--------------------Pull Requests--------------------///

1. Short Description or CheckLists

Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.


///-----------------CheckList-------------------------///


Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x]  I have added tests to cover my changes.
- [x]  All new and existing tests passed.
- [ ] starred the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-10 05:42 UTC, siddhi-244 commented
@PrashantVIT1  why have uh deleted the file?

2022-03-12 11:21 UTC, Lakhankumawat commented
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms)
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md)
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-12 12:25 UTC, PrashantVIT1 commented
Ok, actually I thought that I will have to reupload it in the correct directory. So I was asking for the correct directory.

2022-03-13 08:09 UTC, siddhi-244 commented on A-Array/Stock_Buy_And_Sell/Stock Buy And Sell.cpp
> +    vector<int> v={7,6,4,3,1};
Could uh take this vector as input ?

2022-03-13 08:57 UTC, PrashantVIT1 commented on A-Array/Stock_Buy_And_Sell/Stock Buy And Sell.cpp
> +    vector<int> v={7,6,4,3,1};
Yahhh sure

2022-03-14 17:42 UTC, PrashantVIT1 commented
If it's done it fine then please merge it. 
I want to create one more pull request

2022-03-19 12:51 UTC, siddhi-244 commented
Link the issue to this pr!

2022-03-19 12:52 UTC, siddhi-244 commented
And also don't check all the tasks. Check those which have been followed by you !

2022-03-20 04:02 UTC, PrashantVIT1 commented
> Link the issue to this pr!
#70

2022-03-23 02:25 UTC, siddhi-244 requested changes
Please follow the folder structure and readme guidelines

2022-03-23 02:42 UTC, PrashantVIT1 commented
Thank you for the suggestion but still can you please elaborate on what changes do you want me to do?

2022-03-23 02:47 UTC, PrashantVIT1 commented
Also, reply back soon as it has been 14days and this contribution is not a part of GSSOC and a few more issues are inline.

2022-03-23 02:49 UTC, siddhi-244 commented
> Thank you for the suggestion but still can you please elaborate on what changes do you want me to do? I am not getting it because I have referred a readme that was present on the repo. So please point out the changes.

Follow the folder structure.  Look at other contributions and follow that.

2022-03-23 02:50 UTC, siddhi-244 commented
There is a common readme for all the files ! But you have made another folder inside A-Array. You just have to upload the cpp file and add the approach in common readme

2022-03-23 13:12 UTC, PrashantVIT1 commented
Thank you for your suggestions. Now I have made the required changes.

2022-03-24 13:54 UTC, PrashantVIT1 commented
What I should do to remove this conflict?

2022-03-25 03:19 UTC, siddhi-244 requested changes
Resolve the merge conflicts!

2022-03-25 03:21 UTC, siddhi-244 commented
> What I should do to remove this conflict?
You can click on resolve conflicts and then see the lines which are causing this conflict !

2022-03-26 04:57 UTC, siddhi-244 approved these changes
LGTM !

2022-03-26 09:40 UTC, PrashantVIT1 commented
what is LGTM

2022-03-27 15:14 UTC, PrashantVIT1 commented
So can you merge it and close this issue. As there are 2 more issues inline.

2022-03-28 04:09 UTC, Lakhankumawat requested changes

2022-03-28 04:09 UTC, Lakhankumawat commented on A-Array/README.md
> +
Instead of output screenshot you need to paste the working image of problem statement 

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-29 11:59 UTC, Lakhankumawat requested changes
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-29 12:00 UTC, Lakhankumawat commented
Go through link in comments

2022-03-30 03:12 UTC, Lakhankumawat approved these changes
LGTM 🎉🌟

2022-03-30 03:13 UTC, merged

2022-03-30 03:14 UTC, Lakhankumawat commented
@all-contributors please add @PrashantVIT1  code ,

2022-03-30 04:33 UTC, PrashantVIT1 commented
Thank you, @Lakhankumawat @siddhi-244 😊✨