Reversing of array
Lakhankumawat/LearnCPP pull request #501
Opened 2022-03-10 10:12 UTC by i-am-aisha

create a file reversing of array.cpp in  which I code 2 methods of reversing any array -->
1. reverse1--->reversing any array with help of auxilliary array in this method first we will copy the elements of first array in auxilliary array in reversing order and then again copying the elements of auxilliary array to main array this will reverse our main array.
2. reverse2-->with the help of two pointers high and low, low will iterate from left to right while high will iterate form right to left until low<high and swapping the high index element with low index element this will reverse our main array.
I code above 2 methods with proper comments and mention  time complexity which is O(n).

## Related Issue
issue no. #498 

## Proposed Changes
- Create a reversing of array.cpp file

## Checklist

- [x ] ✅ My code follows the code style of this project.
- [x ] 📝 My change requires a change to the README.
- [x ] 🎀 I have updated the README accordingly.
- [ x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x ] ✨ I have added tests to cover my changes.
- [x ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
code image 1
![code-image1](https://user-images.githubusercontent.com/100334178/157639816-01e5afb6-4dc2-4cd5-9607-4e9b75c57797.png)

code image 2
![code-image2](https://user-images.githubusercontent.com/100334178/157639917-ebb5a275-fc24-44ba-91f6-4401738e52c3.png)

output:
![output](https://user-images.githubusercontent.com/100334178/157640047-e2d42af8-f551-48a7-9f54-e1a4382982ea.png)

2022-03-12 04:08 UTC, Lakhankumawat commented
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.



///------------------Description -----------------------///

Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-14 13:33 UTC, i-am-aisha commented
conflict resolved👍

2022-03-19 12:40 UTC, siddhi-244 commented on A-Array/Reversing of array.cpp
> +    //Calculating the size of the array
Try to take array as input !

2022-03-20 11:48 UTC, i-am-aisha commented on A-Array/Reversing of array.cpp
> +    //Calculating the size of the array
change the code as well as PR for the same👍

2022-03-21 06:31 UTC, siddhi-244 requested changes
You haven't added the reverse array approach in readme.

2022-03-21 09:38 UTC, i-am-aisha commented
readme updated👍

2022-03-22 02:24 UTC, siddhi-244 requested changes
Algorithm should be the steps of program in simple words And not the code. Please see to it !

2022-03-22 12:45 UTC, i-am-aisha commented
updated👍

2022-03-23 02:15 UTC, siddhi-244 requested changes
You have deleted the entire readme file and then copy pasted the code. Please see to it !

2022-03-23 14:02 UTC, i-am-aisha commented
Updated👍

2022-03-25 14:05 UTC, i-am-aisha commented
I updated everything you said but now  what should I do now like what I have to do to correct it?
can you help me please?

2022-03-25 14:06 UTC, siddhi-244 commented
You can make a fresh new pr then ! And just add your content instead of deleting other's content

2022-03-25 14:23 UTC, i-am-aisha commented
you mean separate pr  only for readme of reversing-of-array?

2022-03-26 04:59 UTC, siddhi-244 commented
close this pr and make a new one with same commits ! Just dont delete the content of whole readme file !

2022-03-26 13:09 UTC, closed without merging