Bipartite Graph
Lakhankumawat/LearnCPP pull request #517
Opened 2022-03-11 13:33 UTC by Mrjoy832

## Related Issue
 #188  

## Proposed Changes
-Added short description about problem statement
-Added code, related input-output

## Checklist

- [X] ✅ My code follows the code style of this project.
- [X] 📝 My change requires a change to the documentation.
- [X] 🎀 I have updated the documentation accordingly.
- [X] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [X] ✨ I have added tests to cover my changes.
- [X] 🚩 All new and existing tests passed.
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [X] 🌟 ed the repo

**Solution of issue #188** 
Added brief description about the **bipartite graph** and explained a code using BFS algorithm 
Here I used 2 inputs for the 1st one I show that the graph is bipartite and 2nd input graph is not bipartite
**APPROACH::**
It is possible to test whether a graph is bipartite or not using a BFS Algorithm
There are 2 ways to check for a bipartite graph:
**1. A graph is a bipartite graph if and only if it is colorable by 2 colors only.**
While doing BFS traversal m the given Graph, each node in the BFS tree is given its parent’s opposite color. If there exists an edge connecting the current vertex to a previously colored vertex with the same color, then we can say that the graph is not bipartite.

**2. A graph is a bipartite graph if and only if it  contains an odd cycle(Cycle contains  Odd number of vertices)**
If a graph contains an odd, we cannot divide the graph such that every adjacent vertex has a different color.  If in the BFS, we find an edge, if both of its endpoints are at the same level, then the graph is not Bipartite and an odd-cycle is found. 

**Here in the explanation, we use the 1st approach of the BFS algorithm to check whether a given graph I bipartite or not.**

## Output Screenshots
   

| INPUT-1
![bipartite1](https://user-images.githubusercontent.com/77873383/156414756-19c3be8b-8aff-4fc7-964d-6e6146782f97.jpg)
 | INPUT-2   |
![bipartite2](https://user-images.githubusercontent.com/77873383/156414868-849bbbb4-6108-46e5-b81f-1d0b3af5b5ba.jpg)

2022-03-13 01:27 UTC, Mrjoy832 commented
@miraj0507  please check it...it was already reviewd but I deleted PR by mastake ..I had messaged you on discord about it ..please check it .

2022-03-14 09:09 UTC, Mrjoy832 commented
@Lakhankumawat  what should I have to  change here ?

2022-03-16 06:33 UTC, siddhi-244 requested changes
I can see you have committed 3 files ! Also you added code in cpp file, you don't need it in readme. Follow proper structure of Readme

2022-03-17 03:28 UTC, Mrjoy832 commented
> I can see you have committed 3 files ! Also you added code in cpp file, you don't need it in readme. Follow proper structure of Readme 

Ok I will update

2022-03-20 09:21 UTC, Mrjoy832 commented
![image](https://user-images.githubusercontent.com/77873383/159155975-3b2a3f3a-5aed-479d-b790-868e0558c8bb.png)
How to solve it? @siddhi-244

2022-03-20 09:43 UTC, Mrjoy832 commented
@siddhi-244  , updated please check

2022-03-22 02:57 UTC, siddhi-244 commented
Check the tasks which are completed by you !

2022-03-22 10:17 UTC, Mrjoy832 commented
> Check the tasks which are completed by you !

@siddhi-244 , done please check

2022-03-22 10:19 UTC, siddhi-244 approved these changes
LGTM

2022-03-22 19:02 UTC, Lakhankumawat requested changes

2022-03-22 19:02 UTC, Lakhankumawat commented on G-Graphs/README.md
>  ---
make a README inside B-BipartiteGraph and add your README there , remove your README edits from outside

2022-03-23 02:27 UTC, Mrjoy832 commented
@Lakhankumawat , updated

2022-03-23 09:09 UTC, merged

2022-03-23 09:10 UTC, Lakhankumawat commented
@all-contributors please add @Mrjoy832 ,

2022-03-23 09:10 UTC, Lakhankumawat commented
@all-contributors please add @Mrjoy832 code ,