First commit.
Lakhankumawat/LearnCPP pull request #561
Opened 2022-03-13 06:20 UTC by uhini0201

## Related Issue
- #60 

## Proposed Changes
- Added the K_query problem
- Created a folder named fenwick tree which has its own readme and also added the problem.
## Additional Info
- Each folder has its individual readme.

## Checklist

- [X] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [X] 🎀 I have updated the README accordingly.
- [X] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [X] ✨ I have added tests to cover my changes.
- [X] 🚩 All new and existing tests passed.
- [X] 🌟 ed the repo

I have added the K_query problem in cpp in details.

This is a very well known algorithm and quite efficient and interesting the world of CP.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | 
| ----------- | 
| Output1  | 
| ![output1](https://user-images.githubusercontent.com/59994163/158047624-fe2e7456-2c4d-4178-a3e2-43faab0e2b4c.jpeg)  |

2022-03-13 06:22 UTC, uhini0201 commented
@miraj0507 @Lakhankumawat Please check the let me know if anything else needed.

2022-03-13 10:06 UTC, Lakhankumawat commented
I see there are zipped files and png files which are not allowed

2022-03-13 10:06 UTC, Lakhankumawat commented
you must have only one c++ file with a README in which everything related to what you have contributed 



You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-13 10:08 UTC, Lakhankumawat commented
Change your Code Directory to this ` LearnCPP/T-Tree/F-FenwickTree/KQuery.cpp and README.md`

2022-03-13 10:08 UTC, Lakhankumawat commented
Change the title of your Pull Request and make it related to your issue or Pr type

2022-03-13 13:23 UTC, uhini0201 commented
Ok I am removing the zip files and the png files are for readme. @Lakhankumawat

2022-03-13 13:32 UTC, uhini0201 commented
@Lakhankumawat Please check now.

2022-03-14 06:44 UTC, uhini0201 commented
@Lakhankumawat please update if anything else is needed.

2022-03-16 17:04 UTC, uhini0201 commented
@Lakhankumawat I guess now this pr is ready to merge. If anything else is needed, please let me know.

2022-03-16 19:19 UTC, uhini0201 reviewed
I have reviewed them

2022-03-16 19:33 UTC, uhini0201 commented
@miraj0507 can you please go through the changes???

2022-03-19 15:11 UTC, uhini0201 commented
@Lakhankumawat @miraj0507 Please check my PR #561 if any other change is required.

2022-03-20 07:20 UTC, uhini0201 commented
@Lakhankumawat

2022-03-23 16:37 UTC, uhini0201 commented
@Lakhankumawat I am waiting for you to update with what else is needed to be added yet. Please tell me the changes??

2022-04-01 14:01 UTC, uhini0201 commented
@Lakhankumawat @miraj0507 I am still waiting for your reply.

2022-04-05 12:59 UTC, Lakhankumawat requested changes

2022-04-05 12:59 UTC, Lakhankumawat commented on F-FenwickTree/K_Query.cpp
> +#include<utility>
it will be great if you add comments to your code

2022-04-05 12:59 UTC, Lakhankumawat commented on F-FenwickTree/Readme.md
> +
Your README looks good ✨

2022-04-05 13:00 UTC, Lakhankumawat commented
And sorry for the delay @miraj0507  is inactive as mentor , i am admin and i only see PR's at the end to merge them reviewing PR's is not my work , hope you understand , but now if you do the mentioned changes i will merge your pr

2022-04-05 13:01 UTC, miraj0507 commented
Don't worry will review your PR soon about Fenwick tree

2022-04-05 14:52 UTC, uhini0201 commented on F-FenwickTree/Readme.md
> +
Thanks a lot, i was not sure of the way i did it.

2022-04-05 15:23 UTC, uhini0201 commented on F-FenwickTree/K_Query.cpp
> +#include<stdio.h>
Done Changed the directory to the specified spot. @Lakhankumawat

2022-04-05 15:32 UTC, uhini0201 commented on F-FenwickTree/K_Query.cpp
> +#include<utility>
The comments are added. @Lakhankumawat @miraj0507

2022-04-06 06:02 UTC, Lakhankumawat reviewed
LGTM 🌟

2022-04-06 06:03 UTC, merged

2022-04-06 06:04 UTC, Lakhankumawat commented
@all-contributors please add @uhini0201 code ,