added k-largest elements in array
Lakhankumawat/LearnCPP pull request #587
Opened 2022-03-15 09:37 UTC by SidharthSarangi

## Related Issue
This fixes #586 

### Problem Statement:
Given an array Arr of N positive integers, find K largest elements from the array.  The output elements should be printed in decreasing order.
[Link](https://www.geeksforgeeks.org/k-largestor-smallest-elements-in-an-array/)
### ADDITIONAL INFO
There was no Readme file in the repo/folder so I added the working of both max/min Heap along with time complexity and therefore updated the Readme.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
|Functional code with output vs expected output |
![Screenshot (218)](https://user-images.githubusercontent.com/78564629/158346817-f4bc527d-35e3-4e66-8a3a-59d00b6a8904.png)
|Test Cases Passed|
![Screenshot (219)](https://user-images.githubusercontent.com/78564629/158347097-e1f8ce4d-d101-40bb-abd4-05b9597c81c2.png)

2022-03-15 09:42 UTC, SidharthSarangi commented
Please review @Lakhankumawat @siddhi-244 @iamgunjan

2022-03-17 05:26 UTC, Lakhankumawat requested changes
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-17 05:27 UTC, Lakhankumawat commented
Your Code looks okyish but modify your README

2022-03-17 08:18 UTC, SidharthSarangi commented
check now, I have modified the Readme following the guidelines, and I am putting my 100% to make sure this repo gets completed with the proper resources. @Lakhankumawat

2022-03-17 08:32 UTC, Lakhankumawat requested changes

2022-03-17 08:32 UTC, Lakhankumawat commented on H-Heap/README.md
> +# K LARGEST ELEMENTS
follow camel casing , `K Largest Elements`

2022-03-17 08:32 UTC, Lakhankumawat commented on H-Heap/README.md
> +# TABLE OF CONTENTS
Follow Camel Casing `Table of Contents`

2022-03-17 08:32 UTC, Lakhankumawat commented on H-Heap/README.md
> +## EXPLANATION
Camel casing

2022-03-17 08:39 UTC, SidharthSarangi commented on H-Heap/README.md
> +# K LARGEST ELEMENTS
done

2022-03-17 08:40 UTC, SidharthSarangi commented on H-Heap/README.md
> +# TABLE OF CONTENTS
done

2022-03-17 08:41 UTC, SidharthSarangi commented on H-Heap/README.md
> +## EXPLANATION
done

2022-03-18 14:23 UTC, miraj0507 commented
This looks good to me.

2022-03-19 03:36 UTC, Lakhankumawat approved these changes
LGTM 💯👏

2022-03-19 03:36 UTC, merged

2022-03-19 03:37 UTC, Lakhankumawat commented
@all-contributors please add @SidharthSarangi code,