added CyclicSort.cpp in S-SortingAlgorithms
Lakhankumawat/LearnCPP pull request #603
Opened 2022-03-16 09:59 UTC by aniket-24

## Related Issue
- Cyclic Sort  ( #393  )

## Proposed Changes
- Added Cyclic Sort code in C++

## Additional Info
- Added brief description about Cyclic Sort

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [ ] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

2022-03-17 05:01 UTC, Lakhankumawat commented
1. Update README 
2. Misleading Checks Not Starred the repo
3. Short Description

2022-03-23 02:20 UTC, siddhi-244 commented on S-SortingAlgorithms/CyclicSort.cpp
> +    int arr[] = {5, 4, 3, 2, 1};
Take the array as input

2022-03-23 02:21 UTC, siddhi-244 requested changes
Try to take array as input ! Also you haven't added the approach in Readme

2022-03-23 15:31 UTC, aniket-24 commented
> Try to take array as input ! Also you haven't added the approach in Readme

OKAY!!

2022-05-07 16:48 UTC, closed without merging