Cycle in Linked List code completed.
Lakhankumawat/LearnCPP pull request #615
Opened 2022-03-17 05:26 UTC by dev24il

**# Issue 415**
Cycle in Linked list #415 

**Proposed Changes**
- C++ code file added for cycle in linked list
[README.md](https://github.com/Lakhankumawat/LearnCPP/files/8281620/README.md)

The issue #415  was assigned to me and I completed the code alongwith README file. I have made a C++ file to detect cycle in linked list.
Approach used: Floyd's algorithm
-This is the fastest method to detect cycle in linked list
- Traverse linked list by using two pointers.
- Move one pointer(slow) by one step and second pointer(fast) by two step.
- If these pointers meet at the same node then there is a cycle. If pointers do not meet then linked list doesn’t have a cycle present.

**Complexity Analysis:**

**Time Complexity: O(n)**
Only one traversal of the loop is needed.
**Space Complexity: O(1)**
There is no space required.

OUTPUT SCRRENSHOTS:
Title - Cycle present
![Screenshot (482)](https://user-images.githubusercontent.com/98025162/158742952-751b8a7e-64fb-4dc1-b562-c5ca2e5ec386.png)

Title - Cycle not present
![Screenshot (483)](https://user-images.githubusercontent.com/98025162/158742976-f8234523-0395-4247-a8c9-a38100c6bd03.png)

2022-03-17 05:32 UTC, Lakhankumawat requested changes
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)



Change Directory for code and README to LearnCPP/S-SinglyLinkedList/CycleDetection.cpp and README.md

2022-03-17 05:33 UTC, Lakhankumawat commented
It is great you just skip all the checks

2022-03-17 05:33 UTC, Lakhankumawat commented
Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?

2022-03-18 14:19 UTC, miraj0507 reviewed
Kindly update the checklist as [x]

2022-03-18 14:19 UTC, miraj0507 commented on L-LinkedList/S-SinglyLinkedList/CycleDetection/CycleDetection.cpp
> +    bool detect = detectCycle(head);
Kindly update this to user input style and not the hardcoded way of coding.

2022-03-18 14:19 UTC, miraj0507 commented on L-LinkedList/S-SinglyLinkedList/CycleDetection/CycleDetection.cpp
> +
Why did you keep these two functions when its just cycle detection?

2022-03-19 03:44 UTC, dev24il commented on L-LinkedList/S-SinglyLinkedList/CycleDetection/CycleDetection.cpp
> +
ok

2022-03-23 01:51 UTC, miraj0507 commented
This looks good to me, let's proceed further

2022-03-23 19:58 UTC, n4i9kita commented on L-LinkedList/S-SinglyLinkedList/CycleDetection/CycleDetection.cpp
> +        if (temp == -1){
I don't understand this `if` statement. Why would a user input -1? 
I think you should write some comment, or through output statement.

2022-03-23 19:58 UTC, n4i9kita commented on L-LinkedList/S-SinglyLinkedList/CycleDetection/CycleDetection.cpp
> +    node *current = new node(-1);
You should declare the `current` node in the `else` block. What if the user inputs -1? 
Will there be any use of memory allocation in that case?

2022-03-23 19:58 UTC, n4i9kita commented on L-LinkedList/S-SinglyLinkedList/CycleDetection/CycleDetection.cpp
> +            current -> next = current;
Please explain this to me.

`current -> next = current;` I am not able to understand it. Is it not a self loop?
How are you linking the node `currend` to the list for which we know `head`?

2022-03-23 19:58 UTC, n4i9kita commented on L-LinkedList/S-SinglyLinkedList/CycleDetection/README.md
> +- There is no space required.
Please be careful with what you write.

2022-03-23 19:58 UTC, n4i9kita commented on L-LinkedList/S-SinglyLinkedList/CycleDetection/README.md
> +- This is the fastest method to detect cycle in linked list
Line no. 26 and 68 are same.

2022-03-23 19:58 UTC, n4i9kita commented on L-LinkedList/S-SinglyLinkedList/CycleDetection/README.md
> +- Use of Two pointers
I think you should explain this.
What is the issue if I use two pointers?

2022-03-26 15:22 UTC, closed without merging