Segment Tree Code Added
Lakhankumawat/LearnCPP pull request #633
Opened 2022-03-18 10:23 UTC by RajAdwaita

## Related Issue
- Mention issue for which this pull request is a part of (please mention issue number # )
- Issue Number - #592 
- Issue - I have added the code for the implementation of segment tree in C++ and also added a proper documentation so that anyone going through it understands the topic well.

## Proposed Changes
- Change 1 -  Added the C++ code for segment tree implementation
- Change 2 - Provided proper documentation for the topic.

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [ ] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

I added the code for segment tree implementation and also explained the concept in the readme file

Added segmentTree.cpp and README.md

The Segment tree concept was not solved before and thus I think it adds to the list of concepts already present.

I tested the code using self-declared inputs.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      
![Screenshot 2022-03-18 154817](https://user-images.githubusercontent.com/76047644/158985150-5ce7024d-9784-4502-80d7-7e69a7ffdb20.png)
| ----------- | ----------- |
| Segment Tree  |
| Output for the executed Code |

2022-03-25 13:19 UTC, Lakhankumawat requested changes

2022-03-25 13:19 UTC, Lakhankumawat commented on S-SegmentTree/README.md
> +
Instead of single `#` use triple `###` to reduce size of heading

2022-03-25 13:19 UTC, Lakhankumawat commented on S-SegmentTree/README.md
> +# SEGMENT TREE
here only double `##`

2022-03-25 13:19 UTC, Lakhankumawat commented on S-SegmentTree/segmentTree.cpp
> +#include <bits/stdc++.h>
Change Folder directory and file name to `T-Tree/S-SegmentTree/SegmentTree.cpp` `S-SegmentTree/README.md`

2022-03-25 13:19 UTC, Lakhankumawat commented on S-SegmentTree/segmentTree.cpp
> +}
Add comments inside code

2022-03-25 13:20 UTC, Lakhankumawat commented
**1. Starr the Repo
2. Complete the incomplete checks and check the checks which apply to u in PR description.**

2022-03-28 13:48 UTC, RajAdwaita commented
Just made the naming changes to the code.
Will do the commenting soon.

2022-04-06 10:56 UTC, RajAdwaita commented
@Lakhankumawat please can you review my updates

2022-04-15 03:56 UTC, RajAdwaita commented
@Lakhankumawat @eltociear @Lucifer4255 @ujjwalban can I have a review done for my PR

2022-04-21 17:28 UTC, closed without merging