Quick Sort on DLL
Lakhankumawat/LearnCPP pull request #651
Opened 2022-03-19 08:43 UTC by nickel-28

## Related Issue
- QuickSort on Doubly Linked List (https://github.com/Lakhankumawat/LearnCPP/issues/631)

## Proposed Changes
- Added C++ implementation of Quick Sort on DLL
- Added its Readme file as well

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Test Case 1 | Test Case 2 |
| ![QS_DLL1](https://user-images.githubusercontent.com/84437844/159114210-42e6ed68-5119-4768-b0c3-c634d034cc19.png)  | ![QS_DLL2](https://user-images.githubusercontent.com/84437844/159114245-07e0cfe6-5d12-46e0-ad7d-d52aed9a1eb4.png)     |

2022-03-19 12:51 UTC, Lakhankumawat requested changes
Delete this cocktail sort file https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/CountingSort.cpp duplicate

2022-03-19 12:53 UTC, Lakhankumawat requested changes
Change code directory to `L-LinkedList/D-DoubleLinkedList/QuickSortDLL.cpp `and README.md changes in here

2022-03-19 12:53 UTC, Lakhankumawat commented
You can still modify readme further


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-19 12:54 UTC, Lakhankumawat commented
Overall your contribution looks good

2022-03-22 18:35 UTC, nickel-28 reviewed
Yeah done as you have said me to do...Please review it

2022-03-23 14:37 UTC, miraj0507 commented
LGTM

2022-03-23 19:39 UTC, n4i9kita commented on S-SortingAlgorithms/README.md
> +  - [Cocktail Sort](#cocktail-sort)
Please remove this commit. It is unrelated to your pr.

2022-03-23 19:39 UTC, n4i9kita commented on L-LinkedList/Quick Sort on Doubly Linked List/README.md
> + 1. At first we need to create a node. So we will define a class Node
Could you tell me what does these steps tell? 
It will be better to provide a heading.

Even though you wrote in proper English, a large portion of it is redundant. Make your sentences shorter.

2022-03-23 19:39 UTC, n4i9kita commented on L-LinkedList/Quick Sort on Doubly Linked List/QuickSortOnDoublyLinkedList.cpp
> +Node *lastNode(Node *root)
I think, during function return, we  write it as `Node* lastNode(Node *root)`. 
There isn't anything wrong in the code, but it is just a convention that is followed.

2022-03-23 19:39 UTC, n4i9kita commented on L-LinkedList/Quick Sort on Doubly Linked List/QuickSortOnDoublyLinkedList.cpp
> +    Node *a = NULL;
Preferably, take the DLL as in input from the user.

2022-04-19 16:34 UTC, n4i9kita commented
This PR was regarding Quick sort. Why have you committed the code for `cocktail sort` as well ?

2022-05-20 08:01 UTC, aditi944 commented
closed

2022-05-20 08:01 UTC, closed without merging