Number of leaf nodes in binary tree
Lakhankumawat/LearnCPP pull request #657
Opened 2022-03-19 15:24 UTC by Purvak-10

## Binary Tree
- Number of leaf nodes in binary tree, issue number #656 

## I added an algorithms to find:
-Number of leaf nodes in the binary tree
Some outputs with screenshots are given down below.

## Checklist

- [ ] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [ ] 🎀 I have updated the README accordingly.
- [ ] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots

Output 1:
  ```
                 30
           /              \
        20                40
     /    \             /      \
  10       25          35      45

```
No. of leaf nodes in tree: 4

![Picture1](https://user-images.githubusercontent.com/76229635/159127018-5641f276-820f-47e9-a78f-122da6767d7c.png)

Output 2:
```
100
  \
   120
      \
      130
         \
         140
            \
            150
              \
              160
                 \
                 170
```
No. of leaf nodes of tree: 1

![Picture2](https://user-images.githubusercontent.com/76229635/159127064-4dacff45-0e2e-4c74-a1b4-569ae7e47ec8.png)

2022-03-19 15:26 UTC, Purvak-10 commented
@Lakhankumawat @miraj0507 sir, please check my pull request.

2022-03-20 04:45 UTC, Lakhankumawat requested changes

2022-03-20 04:45 UTC, Lakhankumawat commented on T-Tree/B-BinaryTree/No_of_Leaf_Nodes/No_of_leaf_nodes.cpp
> +#include <bits/stdc++.h>
Change File directory to `T-Tree/B-BinaryTree/No_of_leaf_nodes.cpp` and README Changes in the end for your newly added c++ file

2022-03-20 04:45 UTC, Lakhankumawat commented on T-Tree/B-BinaryTree/No_of_Leaf_Nodes/No_of_leaf_nodes.cpp
> +struct Node* tree(Node* t, int v){
Add comments in code

2022-03-20 04:47 UTC, Lakhankumawat requested changes

2022-03-20 04:47 UTC, Lakhankumawat commented on T-Tree/B-BinaryTree/No_of_Leaf_Nodes/Readme.md
> +- Number of leaf nodes in Binary Tree.
Your Table of content should be like this https://github.com/Lakhankumawat/LearnCPP/blob/main/T-Tree/G-GenricTree/README.md

2022-03-20 04:47 UTC, Lakhankumawat commented on T-Tree/B-BinaryTree/No_of_Leaf_Nodes/Readme.md
> +
Remove these preview and output screenshots instead you need to show only one working image of your code 
See here https://github.com/Lakhankumawat/LearnCPP/blob/main/T-Tree/G-GenricTree/README.md

2022-03-20 04:47 UTC, Lakhankumawat commented on T-Tree/B-BinaryTree/No_of_Leaf_Nodes/Readme.md
> +
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-20 13:21 UTC, Purvak-10 commented on T-Tree/B-BinaryTree/No_of_Leaf_Nodes/Readme.md
> +
@Lakhankumawat sir, how to show working of process, should i explain it?

2022-03-20 15:17 UTC, Purvak-10 commented
@miraj0507 sir, please check the pr i have made the changes

2022-03-23 06:36 UTC, siddhi-244 commented on T-Tree/B-BinaryTree/Readme.md
> +
Add space Complexity too

2022-03-29 11:45 UTC, Purvak-10 commented on T-Tree/B-BinaryTree/Readme.md
> +
@siddhi-244 please review this, i have done the editing.

2022-03-29 11:50 UTC, siddhi-244 requested changes
Try to link the table of contents to actual headings. You can refer other prs !

2022-03-29 11:57 UTC, Lakhankumawat commented
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-29 11:58 UTC, Lakhankumawat commented
Instead of output screenshot in README add working images

2022-03-29 12:07 UTC, Purvak-10 commented
> Instead of output screenshot in README add working images

what is mean of working images? can you please elaborate it

2022-03-29 16:02 UTC, Purvak-10 commented
> Try to link the table of contents to actual headings. You can refer other prs !

@siddhi-244 please review, i have done the editing & mam "what is working images?". If it mean about inputs so for that instead of photos, i have already put in it in words because i think that won't look good if i illustrate my example on a paper.

2022-04-15 14:45 UTC, siddhi-244 approved these changes
LGTM

2022-04-15 17:16 UTC, Lakhankumawat approved these changes
LGTM 🎉✨

2022-04-15 17:17 UTC, merged

2022-04-15 17:17 UTC, Lakhankumawat commented
@all-contributors please add @Purvak-10 code ,