Create Queue_Implementation_without_STL.c++
Lakhankumawat/LearnCPP pull request #665
Opened 2022-03-20 06:48 UTC by ReejoJoseph1244

Added Queue_Implementation _without_STL.c++ file in which all Queue operation is performed in a class and  using this class anyone can call and do the operations on Queue DataStructure.

## Related Issue
#423 

## Proposed Changes
- Created a Queue Implementation file with STL library.
- Changed the README file in the https://github.com/Lakhankumawat/LearnCPP/tree/main/Q-Queue Folder ealier it was Blank.

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      |
### First Testcase
![ouput1](https://user-images.githubusercontent.com/92742868/159151089-c3652f7f-e2a8-4091-9c5a-e88c61cfafea.png)
### 1st Output
![ouput1](https://user-images.githubusercontent.com/92742868/159151013-3293125e-9322-4129-baff-027d5a17f2b1.png)

 | Screenshot #2  |
### Second Testcase
![ouput1](https://user-images.githubusercontent.com/92742868/159151260-54157a32-627f-46c9-b4c7-e23c2294e0f0.png)
### 2nd Output
![ouput1](https://user-images.githubusercontent.com/92742868/159151484-8b8413a7-3be5-4dde-8d45-938da6008f5c.png)

2022-03-20 07:30 UTC, Lakhankumawat requested changes
Rename file to `QueueNoSTL.cpp` and you have to also modify README

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-20 07:30 UTC, Lakhankumawat commented on Q-Queue/Queue_Implementation_without_STL.c++
> +    q1.Display();
Add a swich case statement types here to enqueue and take input from user so that he/she can add live input and display enque deque operations .

2022-03-23 14:34 UTC, miraj0507 commented
Hello, contributor, the readme file is also missing, as pointed by the admin kindly work on the user input style of coding

2022-04-11 11:13 UTC, ReejoJoseph1244 commented on Q-Queue/Queue_Implementation_without_STL.c++
> +    q1.Display();
ok i will do the changes , i have made the changes in the readme file but yes its not visible with this PR. i will take care of that . should i need to make a new pr for updation of readme?

2022-04-23 08:38 UTC, miraj0507 commented
Nop updates from your side?

2022-05-07 16:14 UTC, miraj0507 commented
No further updates and I shall close the PR

2022-05-09 19:20 UTC, ReejoJoseph1244 commented
can i make a new pr for updating the readme file or should i update in the same pr?

2022-05-09 19:30 UTC, ReejoJoseph1244 commented
Hi , 
I have created a new Pr for updated Readme file Pr:- #1402 kindly please check.
Thanks for the reminder

2022-06-12 11:19 UTC, closed without merging