Create DNF Sort File
Lakhankumawat/LearnCPP pull request #682
Opened 2022-03-20 17:20 UTC by Pranshu321

## Related Issue
- #119

## Proposed Changes
- DNF Sort code and full explanation provided. 

## Additional Info
- In this, I deeply explain about the DNF sort how it works.
- What's its time and Space Complexity?
- And its Approach and Algorithm.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

In this pull request, all the things which are required by the beginner for understanding the **DNF Sort** all things are defined in great detail, with simple language, and all points are covered.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

2022-03-27 06:15 UTC, Lakhankumawat requested changes
add comments to your code

2022-03-27 06:15 UTC, Lakhankumawat requested changes

2022-03-27 06:15 UTC, Lakhankumawat commented on S-SortingAlgorithms/README.md
> +
Here add a working image of your sorting algorithm
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-27 06:16 UTC, Lakhankumawat commented
### 1. Starr the REPO

2022-04-05 14:56 UTC, miraj0507 commented
This looks good to me

2022-04-14 07:57 UTC, Pranshu321 commented
> This looks good to me

@miraj0507 sir, Please check now, and really sorry for late response.

2022-04-15 15:06 UTC, Pranshu321 commented
DNF sort algorithm is already present.

2022-04-15 15:06 UTC, closed without merging