Added Deque Directory
Lakhankumawat/LearnCPP pull request #692
Opened 2022-03-21 14:18 UTC by eshaan5

## Related Issue
- This PR closes #621 .

## Proposed Changes
- Added a basic implementation of Deque in C++.
- Changed the README of Queue accordingly.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-03-27 06:27 UTC, Lakhankumawat requested changes

2022-03-27 06:27 UTC, Lakhankumawat commented on D-Deque/slidingWindowMaximum.cpp
> +#include <iostream>
Delete this file we only allow one code file with README at a time

2022-03-27 06:27 UTC, Lakhankumawat commented on D-Deque/DequeSTL.cpp
> +#include <iostream>
Change Your code directory your code must be present inside Q-Queue , Deque is a part of Queue and you need to add your changes inside Q-Queue's README.md

2022-03-27 06:28 UTC, Lakhankumawat commented
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.



///------------------Description -----------------------///

Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-04-08 07:37 UTC, eshaan5 commented
Hey @Lakhankumawat !

I've added the changes that you mentioned. Kindly review my PR now.
Thanks

2022-04-23 08:40 UTC, miraj0507 commented
This looks good to me ready to merge @n4i9kita kindly have a look for the same

2022-06-12 11:19 UTC, closed without merging