Ceil Value in BST
Lakhankumawat/LearnCPP pull request #729
Opened 2022-03-24 07:12 UTC by Mrjoy832

## Related Issue
- Mention issue for which this pull request is a part of (please mention issue number # )
- #711 
## Proposed Changes
- i) Added Code and Output to find Ceil value in BST
-  ii) Updated readme file of LearnCPP/T-Tree/B-BinarySearchTree/Ceil Value BST

## Additional Info
- Added the code with minimal approach of O(h) time complexity.

## Checklist

- [X] ✅ My code follows the code style of this project.
- [X] 📝 My change requires a change to the README.
- [X] 🎀 I have updated the README accordingly.
- [X] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [X] ✨ I have added tests to cover my changes.
- [X] 🚩 All new and existing tests passed.
- [X] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots

2022-03-24 07:19 UTC, Mrjoy832 commented
**1st Merged PR->**  https://github.com/Lakhankumawat/LearnCPP/pull/517
**2ndMerged PR->** https://github.com/Lakhankumawat/LearnCPP/pull/726

2022-03-28 04:20 UTC, Lakhankumawat requested changes

2022-03-28 04:20 UTC, Lakhankumawat commented on T-Tree/B-BinarySearchTree/Ceil Value in BST/readme.md
> +# EXAMPLE =>
instead of single `#` add triple `###` decrease the font size of heading ....

2022-03-28 04:20 UTC, Lakhankumawat commented on T-Tree/B-BinarySearchTree/Ceil Value in BST/readme.md
> +# Approach to find Ceil Value in BST:
###

2022-03-28 04:20 UTC, Lakhankumawat commented on T-Tree/B-BinarySearchTree/Ceil Value in BST/readme.md
> +# Time & Space Complexity :
###

2022-03-28 04:20 UTC, Lakhankumawat commented on T-Tree/B-BinarySearchTree/Ceil Value in BST/readme.md
> +# Ceil Value in Binary Seacrh Tree(BST)
##

2022-03-28 05:28 UTC, Mrjoy832 commented on T-Tree/B-BinarySearchTree/Ceil Value in BST/readme.md
> +# Time & Space Complexity :
Updated

2022-03-28 05:28 UTC, Mrjoy832 commented on T-Tree/B-BinarySearchTree/Ceil Value in BST/readme.md
> +# EXAMPLE =>
> instead of single `#` add triple `###` decrease the font size of heading ....

Readme Updated @Lakhankumawat

2022-03-28 13:33 UTC, Lakhankumawat approved these changes
LGTM 🌟🎉

2022-03-28 13:34 UTC, merged

2022-03-28 13:35 UTC, Lakhankumawat commented
Work on your README's you can still modify them , look how are other README's inside the REPO , next time i won't allow minor mistakes in README of your PR

2022-03-28 13:37 UTC, Lakhankumawat commented
![erw](https://user-images.githubusercontent.com/55774240/160409745-32a473a1-5df8-450c-a4ab-b3a905a16400.png)


Issues 
1. unusual horizontal lines
2. unusual side rules 
3. and big size for headings infact i mentioned ealier to use `###` instead of `##`

2022-03-28 15:45 UTC, Mrjoy832 commented
> Work on your next README's you can still modify them , look how are other README's inside the REPO , next time i won't allow minor mistakes in README of your PR 

Ok I will try to modify from next time