Nge
Lakhankumawat/LearnCPP pull request #791
Opened 2022-03-26 09:26 UTC by shr-code

## Related Issue
- Mention issue for which this pull request is a part of (please mention issue number # )

## Proposed Changes
- Change 1
- Chnage 2

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots

![output](https://user-images.githubusercontent.com/84399701/160233365-01c60332-5b9e-47c3-b4d9-aaae55f3917b.png)

2022-03-26 16:32 UTC, Lakhankumawat commented
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.



///------------------Description -----------------------///

Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-26 16:33 UTC, Lakhankumawat commented
Remove Spacing in file names and modify your readme according to mentioned guidelines

2022-04-03 04:17 UTC, shr-code commented
Sir, the problem statement readme or the pr readme?

2022-04-03 04:33 UTC, shr-code commented
Can you please check now?

2022-04-03 07:05 UTC, siddhi-244 requested changes
Follow the readme guidelines! Refer other prs!

2022-04-05 07:45 UTC, shr-code commented
Sorry, I am not getting what to change?

2022-04-05 08:22 UTC, shr-code commented
@siddhi-244 @Lakhankumawat

2022-04-07 03:12 UTC, siddhi-244 requested changes
There are no table of contents in the readme. Follow the readme guidelines! Refer other prs !

2022-04-19 06:19 UTC, shr-code commented
anyone? @Lakhankumawat @siddhi-244

2022-04-20 15:14 UTC, siddhi-244 requested changes
check the spelling of algorithm and explain the approach !

2022-04-20 19:44 UTC, shr-code commented
typos corrected! The approach (is just the visualization of algorithm) which is already explained. @siddhi-244 @Lakhankumawat

2022-04-21 03:10 UTC, siddhi-244 commented
> typos corrected! The approach (is just the visualization of algorithm) which is already explained. @siddhi-244 @Lakhankumawat

Cool !

2022-04-21 03:11 UTC, siddhi-244 requested changes

2022-04-21 03:11 UTC, siddhi-244 commented on S-Stack/NextGreaterElement/nge.cpp
> +	int n = sizeof(arr) / sizeof(arr[0]);
Can you take the array and it's size as input ?

2022-04-21 04:39 UTC, siddhi-244 approved these changes
LGTM

2022-04-21 04:39 UTC, shr-code commented on S-Stack/NextGreaterElement/nge.cpp
> +	int n = sizeof(arr) / sizeof(arr[0]);
Done! @siddhi-244

2022-04-21 11:02 UTC, Lakhankumawat requested changes

2022-04-21 11:02 UTC, Lakhankumawat commented on S-Stack/NextGreaterElement/README.md
> +## Algorithim
Spelling Mistake (Typo)

2022-04-21 11:02 UTC, Lakhankumawat commented on S-Stack/NextGreaterElement/README.md
> +
Remove this section .

2022-04-22 04:39 UTC, shr-code commented on S-Stack/NextGreaterElement/README.md
> +
ok

2022-04-22 04:40 UTC, shr-code commented
@Lakhankumawat done!!

2022-04-22 05:41 UTC, shr-code commented
done @Lakhankumawat

2022-04-23 06:13 UTC, Lakhankumawat approved these changes
LGTM ✨🎉

2022-04-23 06:13 UTC, merged

2022-04-23 06:15 UTC, Lakhankumawat commented
Good Contribution @shr-code  keep learning keep contributing 🎀

Mention your merged Pr numbers in your next prs and if i found them great i'll  increase your level of contribution ,

2022-04-23 06:15 UTC, Lakhankumawat commented
@all-contributors please add @shr-code code ,