Added Kadane's Algorithm and Readme in D-Dynamic Programming Folder
Lakhankumawat/LearnCPP pull request #81
Opened 2022-02-28 18:48 UTC by shivanithorve01

## Related Issue
-#49

## Proposed Changes
- Change 1 = Added Kadane's Algorithm 
- Change 2 = Added Readme for Kadane's Algorithm explaination.

## Additional Info
- I have used popular problem of Largest Sum of Contiguous Subarray to explain this Kadane's Algorithm better.

## Checklist

- [ *] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ *] 🎀 I have updated the documentation accordingly.
- [* ] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [* ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [* ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

2022-03-01 05:13 UTC, Lakhankumawat commented
A mentor will review this pull request shortly , please have patience.

2022-03-01 12:54 UTC, Lakhankumawat approved these changes
LGTM 🚩

2022-03-01 12:55 UTC, Lakhankumawat commented
Please complete your checklist

2022-03-02 15:38 UTC, Lakhankumawat commented
Let me show you how to check the check list , there should be no space inside brackets like `[x]`
- [x] 
## Checklist

<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->

Or you can just check them from outside without doing any of these

- [x] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ)

2022-03-02 16:23 UTC, miraj0507 commented
kindly look at the checklist

2022-03-04 07:44 UTC, Lakhankumawat commented
Mentors Please Review this

2022-03-05 02:22 UTC, n4i9kita commented on D-DynamicProgramming/Kadane's Algorithm/Kadane's Algorithm.cpp
> +  int A[] = { 2, 1, -2, 5, 6, -7, 3 };
1. Wouldn't it be better to go with a more generalized approach? To take the array from the user?
2. Don't you think the comments in line no. 5, 41, 43, 45, 47 are redundant ?

2022-03-05 06:07 UTC, siddhi-244 requested changes
Try to add images as well in the readme. So that the algorithm will be more clear !

2022-03-05 11:10 UTC, miraj0507 commented on D-DynamicProgramming/Kadane's Algorithm/Kadane's Algorithm.cpp
> +        //if max_sum is negative,ignore that max_sum and start curr_sum again from next element
Hello, how does your algorithm run for the following array
[-2,1,-3,4,-1,2,1,-5,4]
The correct answer is 6 , your code shall give 4,
please consider the fact that the test cases shall be negative as well.
so kindly remove curr_sum <max_sum its wrong

2022-03-05 11:11 UTC, miraj0507 commented on D-DynamicProgramming/Kadane's Algorithm/Kadane's Algorithm.cpp
> +  int A[] = { 2, 1, -2, 5, 6, -7, 3 };
correct kindly take user input

2022-03-05 17:39 UTC, shivanithorve01 commented on D-DynamicProgramming/Kadane's Algorithm/Kadane's Algorithm.cpp
> +        //if max_sum is negative,ignore that max_sum and start curr_sum again from next element
@miraj0507 Yes will do that. Thanks for pointing out !

2022-03-05 18:20 UTC, iamgunjan commented
Looks good to me @Lakhankumawat

2022-03-05 18:26 UTC, shivanithorve01 commented on D-DynamicProgramming/Kadane's Algorithm/Kadane's Algorithm.cpp
> +  int A[] = { 2, 1, -2, 5, 6, -7, 3 };
I have made the required changes. @n4i9kita @miraj0507 can you please review it ?

2022-03-05 18:28 UTC, shivanithorve01 commented on D-DynamicProgramming/Kadane's Algorithm/Kadane's Algorithm.cpp
> +  int A[] = { 2, 1, -2, 5, 6, -7, 3 };
> Try to add images as well in the readme. So that the algorithm will be more clear !

@siddhi-244 Is it allowed to add images from the web ? or we have to make it ourselves ?

2022-03-06 06:05 UTC, n4i9kita commented on D-DynamicProgramming/Kadane's Algorithm/Kadane's Algorithm.cpp
> +  int A[] = { 2, 1, -2, 5, 6, -7, 3 };
You can add images from the web. In a comment, you may cite the source (for reference : readme in S-SortingAlgorithm folder)

2022-03-07 13:12 UTC, siddhi-244 approved these changes
LGTM

2022-03-07 13:34 UTC, Lakhankumawat commented
@shivanithorve01  LGTM let's merge your PR 🎉

2022-03-07 13:34 UTC, merged