Update-1
Lakhankumawat/LearnCPP pull request #827
Opened 2022-03-27 16:15 UTC by sushantdbansode

## Related Issue
-Close #728

## Proposed Changes
- Created a Spiral Print array.cpp file in Arrays Section.
- Updated README.md in Arrays Section accordingly and mention about my file in README.md with some test cases and discussed about the algorithm, its Time & Space Complexity, Approach and Explanation of Code, etc... 

## Checklist

- [ ] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [ ] 🎀 I have updated the README accordingly.
- [ ] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1  
CODE IMAGE
![12](https://user-images.githubusercontent.com/97442721/160289957-f869890b-41f5-4546-b565-438344928d8b.png)

![56](https://user-images.githubusercontent.com/97442721/160289962-55e9c596-ad08-4adb-a1e6-9cc9ff852cf4.png)

![31](https://user-images.githubusercontent.com/97442721/160290030-c744fbf8-7878-4d2f-95dc-5863ef6e732b.png)
OUTPUT OF CODE
![55](https://user-images.githubusercontent.com/97442721/160290198-a0339f36-b35d-4fd1-bea9-9cf2dfb66a12.png)

 | Screenshot #2  |
README EDIT 
![98](https://user-images.githubusercontent.com/97442721/160290419-e21537e0-7c3c-4ca5-bcab-3f076d024074.png)

![99](https://user-images.githubusercontent.com/97442721/160290547-761dd805-c636-4979-9c1f-271676d05a80.png)

![100](https://user-images.githubusercontent.com/97442721/160290614-12dc806d-87c6-48dd-a15c-0f0d39a519c5.png)

2022-03-28 04:13 UTC, Lakhankumawat requested changes

2022-03-28 04:13 UTC, Lakhankumawat commented on A-Array/README.md
> +
It would be better if you could add a working image to your README just like in issue you created .

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-03-28 04:14 UTC, Lakhankumawat commented
Uncheck the checks which do not apply to you

2022-04-10 11:28 UTC, sushantdbansode commented
All Reviews Cleared

2022-04-10 11:30 UTC, sushantdbansode reviewed
All Issues Resolved

2022-04-10 12:32 UTC, closed without merging