Coin Change Problem - DP
Lakhankumawat/LearnCPP pull request #895
Opened 2022-03-28 15:07 UTC by Ahmed-walid

## Related Issue
- Coin Change Problem issue #885 

## Proposed Changes
- Implementing a bottom-up approach for Coin Chang Problem with Explanation.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

I have implemented a bottom-up dynamic programming solution for the Coin Change problem provided by tests that cover all scenarios. And updated the README file with an explanation with examples and how to formulate the solution.

To summarize, I have created a new file CoinChange.CPP and updated the README file.

The coin change problem is fundamental and has a lot of variations and is considered a DP pattern so it is very useful, especially for newbies to dynamic programming.

[Coin Change Problem #885] (https://github.com/Lakhankumawat/LearnCPP/issues/885)

I used the main function for testing and submitted it on Leetcode and got accepted.

Tests are:

```
Example 1:
    Input: coins = [1,2,5], amount = 11
    Output: 3
    Explanation: 11 = 5 + 5 + 1

Example 2:
    Input: coins = [2], amount = 3
    Output: -1

```

The change is made in one file (CoinChange.CPP) and does not depend on other files.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| amount = 11 and coins = [1,2,5]  | amount =3 and coins = [2] |
|![image](https://user-images.githubusercontent.com/62077516/160427213-eb068c71-69ac-4d62-9861-bb7c88059316.png) |![image](https://user-images.githubusercontent.com/62077516/160427437-493a5ea9-ba45-4630-abd5-2a052d32d748.png)
|

2022-03-28 15:08 UTC, Ahmed-walid commented
Any feedback is welcomed!

2022-03-29 06:01 UTC, Ahmed-walid commented
@Lakhankumawat can you please review my pull request?

2022-04-02 03:27 UTC, Lakhankumawat requested changes
Rest Looks Good , do the required changes

2022-04-02 03:27 UTC, Lakhankumawat commented on D-DynamicProgramming/README.md
> +# Complexity
add ### instead of one # , decrease size follow exact guidelines mentioned here for readme design

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

2022-04-21 06:19 UTC, siddhi-244 commented on D-DynamicProgramming/CoinChange.cpp
> +    int amount1 = 11;
Can you take this as input?

2022-04-22 00:42 UTC, siddhi-244 commented
I can see 3 files are committed! Can you please see to it ?

2022-04-22 12:20 UTC, Ahmed-walid commented
> 

I think the readme file located in the B-Binary Tree sub-folder is deleted by me. I thin merging will not cause any conflicts at your side.

2022-04-30 05:17 UTC, Lakhankumawat reviewed
## Deleted Necessary Files From BinaryTree Folder - ❌❌

Create a new PR with the changes of only your DP code and README 
Do fetch upstream first on main otherwise you might get merge conflicts .

2022-04-30 05:17 UTC, Lakhankumawat commented
Create a new PR dm me in discord .

2022-04-30 05:17 UTC, closed without merging